/*
  # إضافة حقول الشهادة المتوسطة والثانوية
*/

-- إضافة حقول الشهادة المتوسطة - بيانات المتقدم
INSERT INTO service_fields (service_id, service_type_id, step_id, step_title_ar, step_title_en, field_name, field_type, label_ar, label_en, placeholder_ar, placeholder_en, is_required, order_index, is_active, options) VALUES
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'gender', 'radio', 'النوع', 'Gender', '', '', true, 1, true, '[{"value": "male", "label_ar": "ذكر", "label_en": "Male"}, {"value": "female", "label_ar": "أنثى", "label_en": "Female"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'nationality', 'radio', 'الجنسية', 'Nationality', '', '', true, 2, true, '[{"value": "sudanese", "label_ar": "سوداني", "label_en": "Sudanese"}, {"value": "non-sudanese", "label_ar": "غير سوداني", "label_en": "Non-Sudanese"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'specificNationality', 'text', 'نوع الجنسية', 'Specific Nationality', 'أدخل الجنسية', 'Enter nationality', false, 3, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'fullName', 'text', 'الاسم الرباعي مطابقاً للرقم الوطني', 'Full Name as per National ID', 'أدخل الاسم الرباعي', 'Enter full name', true, 4, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'nationalId', 'text', 'الرقم الوطني / رقم الجواز', 'National ID / Passport Number', 'أدخل الرقم الوطني أو الجواز', 'Enter ID or passport', true, 5, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'dateOfBirth', 'date', 'تاريخ الميلاد', 'Date of Birth', '', '', true, 6, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'motherName', 'text', 'اسم الأم رباعي', 'Mother Full Name', 'أدخل اسم الأم الرباعي', 'Enter mother full name', true, 7, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'schoolName', 'text', 'اسم المدرسة', 'School Name', 'أدخل اسم المدرسة', 'Enter school name', true, 8, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'examLanguage', 'radio', 'لغة الامتحان', 'Exam Language', '', '', true, 9, true, '[{"value": "arabic", "label_ar": "عربي", "label_en": "Arabic"}, {"value": "english", "label_ar": "إنجليزي", "label_en": "English"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'specialCase', 'select', 'حالة خاصة', 'Special Case', 'اختر الحالة', 'Select case', false, 10, true, '[{"value": "", "label_ar": "لا توجد", "label_en": "None"}, {"value": "mobility", "label_ar": "إعاقة حركية", "label_en": "Mobility Disability"}, {"value": "hearing", "label_ar": "إعاقة سمعية", "label_en": "Hearing Disability"}, {"value": "visual", "label_ar": "إعاقة بصرية", "label_en": "Visual Disability"}, {"value": "learning", "label_ar": "صعوبة تعلم", "label_en": "Learning Difficulty"}, {"value": "attention", "label_ar": "تشتت انتباه", "label_en": "Attention Deficit"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'specialCaseDescription', 'textarea', 'وصف الحالة الخاصة', 'Special Case Description', 'اذكر وصف الحالة', 'Describe the case', false, 11, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'mobileNumber', 'tel', 'رقم الجوال', 'Mobile Number', '05xxxxxxxx', '05xxxxxxxx', true, 12, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'addressRegion', 'select', 'المنطقة', 'Region', 'اختر المنطقة', 'Select region', true, 13, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'addressCity', 'select', 'المدينة', 'City', 'اختر المدينة', 'Select city', true, 14, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'addressDistrict', 'select', 'الحي', 'District', 'اختر الحي', 'Select district', false, 15, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'addressLandmark', 'text', 'أقرب معلم', 'Nearest Landmark', 'أدخل أقرب معلم', 'Enter nearest landmark', true, 16, true, NULL);

-- معلومات ولي الأمر - المتوسطة
INSERT INTO service_fields (service_id, service_type_id, step_id, step_title_ar, step_title_en, field_name, field_type, label_ar, label_en, placeholder_ar, placeholder_en, is_required, order_index, is_active) VALUES
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step2', 'معلومات ولي الأمر', 'Guardian Information', 'guardianName', 'text', 'اسم ولي الأمر', 'Guardian Name', 'أدخل اسم ولي الأمر', 'Enter guardian name', true, 17, true),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step2', 'معلومات ولي الأمر', 'Guardian Information', 'guardianPhone', 'tel', 'رقم هاتف ولي الأمر', 'Guardian Phone', '05xxxxxxxx', '05xxxxxxxx', true, 18, true),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step2', 'معلومات ولي الأمر', 'Guardian Information', 'guardianWorkplace', 'text', 'مكان العمل', 'Workplace', 'أدخل مكان العمل', 'Enter workplace', true, 19, true);

-- المستندات - المتوسطة
INSERT INTO service_documents (service_id, service_type_id, document_name_ar, document_name_en, description_ar, description_en, is_required, max_size_mb, accepted_formats, order_index, is_active) VALUES
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'شهادة الأساس أو ما يعادلها', 'Basic Certificate or Equivalent', 'شهادة الأساس أو ما يعادلها مرّ عليها ثلاث سنوات', 'Basic certificate or equivalent (three years old)', true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 1, true),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'صورة شخصية حديثة', 'Recent Personal Photo', 'صورة شخصية حديثة بمقاس صورة الجواز (4×6 سم)', 'Recent passport-size photo (4×6 cm)', true, 2, '["jpg","jpeg","png"]'::jsonb, 2, true),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'الرقم الوطني / الجواز', 'National ID / Passport', 'السودانيون: إرفاق صورة الرقم الوطني | غير السودانيين: إرفاق صورة جواز السفر', 'Sudanese: National ID copy | Non-Sudanese: Passport copy', true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 3, true);

SELECT 'INTERMEDIATE_ADDED' as status;
