/*
  # Add Sample Events Data

  1. Sample Data
    - Inserts 12 sample events in both Arabic and English
    - Includes various event types: workshops, meetings, conferences, cultural events
    - Categorized by date groups (today, tomorrow, afterTomorrow, nextWeek, upcoming)
    - All events are active and some are featured
    - Uses images from Pexels
    
  2. Content
    - Investment workshops
    - Community meetings
    - Cultural exhibitions
    - Training courses
    - National celebrations
    - Business conferences
*/

-- Insert sample events
INSERT INTO events (
  title_ar, title_en,
  description_ar, description_en,
  short_description_ar, short_description_en,
  event_date, event_time,
  location_ar, location_en,
  featured_image,
  tab_group,
  capacity,
  registration_required,
  is_featured,
  is_active,
  organizer_ar,
  organizer_en
) VALUES
(
  'ورشة عمل حول فرص الاستثمار في السودان',
  'Workshop on Investment Opportunities in Sudan',
  'ورشة تفاعلية للتعريف بالفرص الاستثمارية المتاحة في مختلف القطاعات السودانية. تشمل الورشة عروضاً تقديمية من خبراء اقتصاديين، دراسات حالة ناجحة، وجلسات نقاش مفتوحة للإجابة على استفسارات المستثمرين المحتملين.',
  'Interactive workshop introducing available investment opportunities in various Sudanese sectors. The workshop includes presentations by economic experts, successful case studies, and open discussion sessions to answer potential investors'' inquiries.',
  'ورشة تفاعلية للتعريف بالفرص الاستثمارية المتاحة في مختلف القطاعات السودانية',
  'Interactive workshop introducing available investment opportunities in various Sudanese sectors',
  '2025-01-16', '10:00',
  'قاعة المؤتمرات - القنصلية',
  'Conference Hall - Consulate',
  'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=600',
  'today',
  100,
  true,
  true,
  true,
  'القنصلية السودانية',
  'Sudanese Consulate'
),
(
  'لقاء مفتوح مع الجالية السودانية',
  'Open Meeting with Sudanese Community',
  'لقاء مفتوح لمناقشة احتياجات الجالية والإجابة على الاستفسارات. سيكون القنصل العام والموظفون المختصون متواجدين للاستماع إلى ملاحظات واقتراحات أفراد الجالية ومناقشة الخدمات المقدمة وكيفية تحسينها.',
  'Open meeting to discuss community needs and answer inquiries. The Consul General and specialized staff will be present to listen to community members'' comments and suggestions and discuss services provided and how to improve them.',
  'لقاء مفتوح لمناقشة احتياجات الجالية والإجابة على الاستفسارات',
  'Open meeting to discuss community needs and answer inquiries',
  '2025-01-16', '19:00',
  'القاعة الكبرى - القنصلية',
  'Main Hall - Consulate',
  'https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg?auto=compress&cs=tinysrgb&w=600',
  'today',
  150,
  false,
  false,
  true,
  'القنصلية السودانية',
  'Sudanese Consulate'
),
(
  'دورة تدريبية للطلاب السودانيين',
  'Training Course for Sudanese Students',
  'دورة تدريبية متخصصة للطلاب السودانيين حول الفرص التعليمية والمنح الدراسية. تتضمن الدورة معلومات عن المنح المتاحة، كيفية التقديم، متطلبات القبول، ونصائح لتحقيق التفوق الأكاديمي. كما سيتم استضافة طلاب متفوقين لمشاركة تجاربهم.',
  'Specialized training course for Sudanese students on educational opportunities and scholarships. The course includes information about available scholarships, how to apply, admission requirements, and tips for achieving academic excellence. Outstanding students will also be hosted to share their experiences.',
  'دورة تدريبية متخصصة للطلاب السودانيين حول الفرص التعليمية والمنح الدراسية',
  'Specialized training course for Sudanese students on educational opportunities and scholarships',
  '2025-01-16', '14:00',
  'القاعة التدريبية - القنصلية',
  'Training Hall - Consulate',
  'https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=600',
  'today',
  80,
  true,
  true,
  true,
  'وزارة التعليم العالي',
  'Ministry of Higher Education'
),
(
  'احتفالية اليوم الوطني السوداني',
  'Sudanese National Day Celebration',
  'احتفالية خاصة بمناسبة اليوم الوطني مع فعاليات ثقافية وتراثية. يتضمن الحفل عروضاً فنية، معارض تراثية، مأكولات سودانية تقليدية، وفقرات ترفيهية للأطفال. كما سيتم تكريم الشخصيات السودانية البارزة.',
  'Special celebration for National Day with cultural and heritage activities. The celebration includes artistic performances, heritage exhibitions, traditional Sudanese cuisine, and entertainment segments for children. Outstanding Sudanese personalities will also be honored.',
  'احتفالية خاصة بمناسبة اليوم الوطني مع فعاليات ثقافية وتراثية',
  'Special celebration for National Day with cultural and heritage activities',
  '2025-01-17', '18:00',
  'مركز الملك عبدالعزيز الثقافي',
  'King Abdulaziz Cultural Center',
  'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg?auto=compress&cs=tinysrgb&w=600',
  'tomorrow',
  500,
  true,
  true,
  true,
  'القنصلية السودانية',
  'Sudanese Consulate'
),
(
  'معرض الثقافة والتراث السوداني',
  'Sudanese Culture and Heritage Exhibition',
  'معرض شامل يستعرض التراث والثقافة السودانية الأصيلة. يضم المعرض قطعاً أثرية، حرفاً يدوية تقليدية، أزياء شعبية، ولوحات فنية. كما يتضمن ورش عمل تفاعلية لتعليم الحرف اليدوية والفنون التقليدية.',
  'Comprehensive exhibition showcasing authentic Sudanese heritage and culture. The exhibition features antiques, traditional handicrafts, folk costumes, and artistic paintings. It also includes interactive workshops to teach handicrafts and traditional arts.',
  'معرض شامل يستعرض التراث والثقافة السودانية الأصيلة',
  'Comprehensive exhibition showcasing authentic Sudanese heritage and culture',
  '2025-01-17', '16:00',
  'صالة المعارض - القنصلية',
  'Exhibition Hall - Consulate',
  'https://images.pexels.com/photos/1181677/pexels-photo-1181677.jpeg?auto=compress&cs=tinysrgb&w=600',
  'tomorrow',
  200,
  false,
  false,
  true,
  'وزارة الثقافة',
  'Ministry of Culture'
),
(
  'ندوة حول الخدمات القنصلية الجديدة',
  'Seminar on New Consular Services',
  'ندوة تعريفية حول الخدمات القنصلية الجديدة والإجراءات المحدثة. سيتم شرح كافة الخدمات الإلكترونية المتاحة، كيفية استخدامها، والإجابة على أسئلة واستفسارات الحضور. الندوة موجهة لجميع أفراد الجالية السودانية.',
  'Introductory seminar on new consular services and updated procedures. All available electronic services will be explained, how to use them, and answer questions from attendees. The seminar is directed to all members of the Sudanese community.',
  'ندوة تعريفية حول الخدمات القنصلية الجديدة والإجراءات المحدثة',
  'Introductory seminar on new consular services and updated procedures',
  '2025-01-17', '11:00',
  'قاعة الاجتماعات - القنصلية',
  'Meeting Hall - Consulate',
  'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=600',
  'tomorrow',
  120,
  false,
  false,
  true,
  'القنصلية السودانية',
  'Sudanese Consulate'
),
(
  'مؤتمر الاستثمار السوداني السعودي',
  'Sudanese-Saudi Investment Conference',
  'مؤتمر اقتصادي لتعزيز الاستثمارات المشتركة بين السودان والسعودية. يحضر المؤتمر وفود رسمية، رجال أعمال، ومستثمرون من البلدين. سيتم توقيع اتفاقيات تعاون في قطاعات الزراعة، الصناعة، التعدين، والطاقة المتجددة.',
  'Economic conference to promote joint investments between Sudan and Saudi Arabia. The conference is attended by official delegations, businessmen, and investors from both countries. Cooperation agreements will be signed in agriculture, industry, mining, and renewable energy sectors.',
  'مؤتمر اقتصادي لتعزيز الاستثمارات المشتركة بين السودان والسعودية',
  'Economic conference to promote joint investments between Sudan and Saudi Arabia',
  '2025-01-18', '09:00',
  'فندق الريتز كارلتون - جدة',
  'Ritz Carlton Hotel - Jeddah',
  'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=600',
  'afterTomorrow',
  300,
  true,
  true,
  true,
  'وزارة الاستثمار',
  'Ministry of Investment'
),
(
  'أمسية شعرية سودانية',
  'Sudanese Poetry Evening',
  'أمسية شعرية تحتفي بالأدب والشعر السوداني الأصيل. يشارك في الأمسية نخبة من الشعراء السودانيين المقيمين في المملكة لإلقاء قصائدهم وأشعارهم. الأمسية مفتوحة لجميع محبي الأدب والشعر من الجالية السودانية والعربية.',
  'Poetry evening celebrating authentic Sudanese literature and poetry. The evening features a selection of Sudanese poets residing in the Kingdom to recite their poems. The evening is open to all literature and poetry lovers from the Sudanese and Arab communities.',
  'أمسية شعرية تحتفي بالأدب والشعر السوداني الأصيل',
  'Poetry evening celebrating authentic Sudanese literature and poetry',
  '2025-01-18', '20:00',
  'المركز الثقافي - جدة',
  'Cultural Center - Jeddah',
  'https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg?auto=compress&cs=tinysrgb&w=600',
  'afterTomorrow',
  150,
  false,
  false,
  true,
  'اتحاد الأدباء السودانيين',
  'Sudanese Writers Union'
),
(
  'ورشة عمل للحرف اليدوية السودانية',
  'Sudanese Handicrafts Workshop',
  'ورشة تعليمية للحرف اليدوية التقليدية السودانية. سيتم تعليم المشاركين صناعة المشغولات اليدوية التقليدية مثل السلال، الفخار، والمنسوجات. الورشة موجهة للمهتمين بالحفاظ على التراث وتعلم المهارات التقليدية.',
  'Educational workshop on traditional Sudanese handicrafts. Participants will be taught how to make traditional handmade products such as baskets, pottery, and textiles. The workshop is aimed at those interested in preserving heritage and learning traditional skills.',
  'ورشة تعليمية للحرف اليدوية التقليدية السودانية',
  'Educational workshop on traditional Sudanese handicrafts',
  '2025-01-18', '15:00',
  'مركز الفنون - القنصلية',
  'Arts Center - Consulate',
  'https://images.pexels.com/photos/1181677/pexels-photo-1181677.jpeg?auto=compress&cs=tinysrgb&w=600',
  'afterTomorrow',
  50,
  true,
  false,
  true,
  'جمعية الحرف اليدوية',
  'Handicrafts Association'
),
(
  'لقاء رجال الأعمال السودانيين',
  'Sudanese Businessmen Meeting',
  'لقاء تجاري لتبادل الخبرات وتطوير الشراكات التجارية. يهدف اللقاء إلى تعزيز التعاون بين رجال الأعمال السودانيين في المملكة، مناقشة الفرص الاستثمارية، وتبادل الخبرات في مختلف المجالات التجارية والصناعية.',
  'Business meeting to exchange experiences and develop commercial partnerships. The meeting aims to enhance cooperation among Sudanese businessmen in the Kingdom, discuss investment opportunities, and exchange experiences in various commercial and industrial fields.',
  'لقاء تجاري لتبادل الخبرات وتطوير الشراكات التجارية',
  'Business meeting to exchange experiences and develop commercial partnerships',
  '2025-01-23', '10:00',
  'قاعة الأعمال - فندق الهيلتون',
  'Business Hall - Hilton Hotel',
  'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=600',
  'nextWeek',
  100,
  true,
  false,
  true,
  'جمعية رجال الأعمال السودانيين',
  'Sudanese Businessmen Association'
),
(
  'مهرجان الطعام السوداني',
  'Sudanese Food Festival',
  'مهرجان للتعريف بالمأكولات السودانية التقليدية والشعبية. يتضمن المهرجان أكشاك طعام تقدم أشهر الأطباق السودانية، عروض طبخ حية، ومسابقات طهي. المهرجان مفتوح للجميع من الجالية السودانية والسعودية.',
  'Festival introducing traditional and popular Sudanese cuisine. The festival includes food stalls offering the most famous Sudanese dishes, live cooking shows, and cooking competitions. The festival is open to all from the Sudanese and Saudi communities.',
  'مهرجان للتعريف بالمأكولات السودانية التقليدية والشعبية',
  'Festival introducing traditional and popular Sudanese cuisine',
  '2025-01-24', '17:00',
  'حديقة الأندلس - جدة',
  'Al-Andalus Park - Jeddah',
  'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg?auto=compress&cs=tinysrgb&w=600',
  'nextWeek',
  500,
  false,
  true,
  true,
  'القنصلية السودانية',
  'Sudanese Consulate'
),
(
  'دورة اللغة العربية للأطفال',
  'Arabic Language Course for Children',
  'دورة تعليمية للأطفال السودانيين لتعزيز اللغة العربية. تستهدف الدورة الأطفال من سن 6 إلى 12 سنة وتركز على القراءة، الكتابة، والمحادثة باللغة العربية الفصحى. تستمر الدورة لمدة شهرين بواقع جلستين أسبوعياً.',
  'Educational course for Sudanese children to enhance Arabic language skills. The course targets children aged 6 to 12 years and focuses on reading, writing, and speaking in classical Arabic. The course lasts for two months with two sessions per week.',
  'دورة تعليمية للأطفال السودانيين لتعزيز اللغة العربية',
  'Educational course for Sudanese children to enhance Arabic language skills',
  '2025-01-25', '16:00',
  'قاعة التعليم - القنصلية',
  'Education Hall - Consulate',
  'https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=600',
  'nextWeek',
  40,
  true,
  false,
  true,
  'مركز تعليم اللغة العربية',
  'Arabic Language Education Center'
)
ON CONFLICT DO NOTHING;
