-- إضافة حقول الشهادة الابتدائية
-- Step 1: بيانات المتقدم
INSERT INTO service_fields (service_id, service_type_id, step_id, step_title_ar, step_title_en, field_name, field_type, label_ar, label_en, placeholder_ar, placeholder_en, is_required, order_index, is_active, options) VALUES
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step1', 'بيانات المتقدم', 'Applicant Information', 'gender', 'radio', 'النوع', 'Gender', '', '', true, 1, true, '[{"value": "male", "label_ar": "ذكر", "label_en": "Male"}, {"value": "female", "label_ar": "أنثى", "label_en": "Female"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step1', 'بيانات المتقدم', 'Applicant Information', 'nationality', 'radio', 'الجنسية', 'Nationality', '', '', true, 2, true, '[{"value": "sudanese", "label_ar": "سوداني", "label_en": "Sudanese"}, {"value": "non-sudanese", "label_ar": "غير سوداني", "label_en": "Non-Sudanese"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step1', 'بيانات المتقدم', 'Applicant Information', 'specificNationality', 'text', 'نوع الجنسية', 'Specific Nationality', 'أدخل الجنسية', 'Enter nationality', false, 3, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step1', 'بيانات المتقدم', 'Applicant Information', 'fullName', 'text', 'الاسم الرباعي مطابقاً للرقم الوطني', 'Full Name as per National ID', 'أدخل الاسم الرباعي', 'Enter full name', true, 4, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step1', 'بيانات المتقدم', 'Applicant Information', 'nationalId', 'text', 'الرقم الوطني / رقم الجواز', 'National ID / Passport Number', 'أدخل الرقم الوطني أو الجواز', 'Enter ID or passport', true, 5, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step1', 'بيانات المتقدم', 'Applicant Information', 'dateOfBirth', 'date', 'تاريخ الميلاد', 'Date of Birth', '', '', true, 6, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step1', 'بيانات المتقدم', 'Applicant Information', 'motherName', 'text', 'اسم الأم رباعي', 'Mother Full Name', 'أدخل اسم الأم الرباعي', 'Enter mother full name', true, 7, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step1', 'بيانات المتقدم', 'Applicant Information', 'schoolName', 'text', 'اسم المدرسة', 'School Name', 'أدخل اسم المدرسة', 'Enter school name', true, 8, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step1', 'بيانات المتقدم', 'Applicant Information', 'examLanguage', 'radio', 'لغة الامتحان', 'Exam Language', '', '', true, 9, true, '[{"value": "arabic", "label_ar": "عربي", "label_en": "Arabic"}, {"value": "english", "label_ar": "إنجليزي", "label_en": "English"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step1', 'بيانات المتقدم', 'Applicant Information', 'specialCase', 'select', 'حالة خاصة', 'Special Case', 'اختر الحالة', 'Select case', false, 10, true, '[{"value": "", "label_ar": "لا توجد", "label_en": "None"}, {"value": "mobility", "label_ar": "إعاقة حركية", "label_en": "Mobility Disability"}, {"value": "hearing", "label_ar": "إعاقة سمعية", "label_en": "Hearing Disability"}, {"value": "visual", "label_ar": "إعاقة بصرية", "label_en": "Visual Disability"}, {"value": "learning", "label_ar": "صعوبة تعلم", "label_en": "Learning Difficulty"}, {"value": "attention", "label_ar": "تشتت انتباه", "label_en": "Attention Deficit"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step1', 'بيانات المتقدم', 'Applicant Information', 'specialCaseDescription', 'textarea', 'وصف الحالة الخاصة', 'Special Case Description', 'اذكر وصف الحالة', 'Describe the case', false, 11, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step1', 'بيانات المتقدم', 'Applicant Information', 'mobileNumber', 'tel', 'رقم الجوال', 'Mobile Number', '05xxxxxxxx', '05xxxxxxxx', true, 12, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step1', 'بيانات المتقدم', 'Applicant Information', 'addressRegion', 'select', 'المنطقة', 'Region', 'اختر المنطقة', 'Select region', true, 13, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step1', 'بيانات المتقدم', 'Applicant Information', 'addressCity', 'select', 'المدينة', 'City', 'اختر المدينة', 'Select city', true, 14, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step1', 'بيانات المتقدم', 'Applicant Information', 'addressDistrict', 'select', 'الحي', 'District', 'اختر الحي', 'Select district', false, 15, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step1', 'بيانات المتقدم', 'Applicant Information', 'addressLandmark', 'text', 'أقرب معلم', 'Nearest Landmark', 'أدخل أقرب معلم', 'Enter nearest landmark', true, 16, true, NULL);

-- Step 2: معلومات ولي الأمر
INSERT INTO service_fields (service_id, service_type_id, step_id, step_title_ar, step_title_en, field_name, field_type, label_ar, label_en, placeholder_ar, placeholder_en, is_required, order_index, is_active) VALUES
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step2', 'معلومات ولي الأمر', 'Guardian Information', 'guardianName', 'text', 'اسم ولي الأمر', 'Guardian Name', 'أدخل اسم ولي الأمر', 'Enter guardian name', true, 17, true),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step2', 'معلومات ولي الأمر', 'Guardian Information', 'guardianPhone', 'tel', 'رقم هاتف ولي الأمر', 'Guardian Phone', '05xxxxxxxx', '05xxxxxxxx', true, 18, true),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'step2', 'معلومات ولي الأمر', 'Guardian Information', 'guardianWorkplace', 'text', 'مكان العمل', 'Workplace', 'أدخل مكان العمل', 'Enter workplace', true, 19, true);

-- Step 3: المستندات المطلوبة
INSERT INTO service_documents (service_id, service_type_id, document_name_ar, document_name_en, description_ar, description_en, is_required, max_size_mb, accepted_formats, order_index, is_active) VALUES
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'أصل شهادة الصف الخامس', 'Original Grade 5 Certificate', 'أصل شهادة الصف الخامس مرّ عليها عام', 'Original grade 5 certificate (one year old)', true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 1, true),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'صورة شخصية حديثة', 'Recent Personal Photo', 'صورة شخصية حديثة بمقاس صورة الجواز (4×6 سم)', 'Recent passport-size photo (4×6 cm)', true, 2, '["jpg","jpeg","png"]'::jsonb, 2, true),
((SELECT id FROM services WHERE slug = 'education'), 'a70fcb7e-039e-427b-89ea-ff253bb41dbd', 'الرقم الوطني / الجواز', 'National ID / Passport', 'السودانيون: إرفاق صورة الرقم الوطني | غير السودانيين: إرفاق صورة جواز السفر', 'Sudanese: National ID copy | Non-Sudanese: Passport copy', true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 3, true);

-- ============================================
-- إضافة حقول الشهادة المتوسطة
-- ============================================
-- Step 1: بيانات المتقدم
INSERT INTO service_fields (service_id, service_type_id, step_id, step_title_ar, step_title_en, field_name, field_type, label_ar, label_en, placeholder_ar, placeholder_en, is_required, order_index, is_active, options) VALUES
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'gender', 'radio', 'النوع', 'Gender', '', '', true, 1, true, '[{"value": "male", "label_ar": "ذكر", "label_en": "Male"}, {"value": "female", "label_ar": "أنثى", "label_en": "Female"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'nationality', 'radio', 'الجنسية', 'Nationality', '', '', true, 2, true, '[{"value": "sudanese", "label_ar": "سوداني", "label_en": "Sudanese"}, {"value": "non-sudanese", "label_ar": "غير سوداني", "label_en": "Non-Sudanese"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'specificNationality', 'text', 'نوع الجنسية', 'Specific Nationality', 'أدخل الجنسية', 'Enter nationality', false, 3, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'fullName', 'text', 'الاسم الرباعي مطابقاً للرقم الوطني', 'Full Name as per National ID', 'أدخل الاسم الرباعي', 'Enter full name', true, 4, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'nationalId', 'text', 'الرقم الوطني / رقم الجواز', 'National ID / Passport Number', 'أدخل الرقم الوطني أو الجواز', 'Enter ID or passport', true, 5, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'dateOfBirth', 'date', 'تاريخ الميلاد', 'Date of Birth', '', '', true, 6, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'motherName', 'text', 'اسم الأم رباعي', 'Mother Full Name', 'أدخل اسم الأم الرباعي', 'Enter mother full name', true, 7, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'schoolName', 'text', 'اسم المدرسة', 'School Name', 'أدخل اسم المدرسة', 'Enter school name', true, 8, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'examLanguage', 'radio', 'لغة الامتحان', 'Exam Language', '', '', true, 9, true, '[{"value": "arabic", "label_ar": "عربي", "label_en": "Arabic"}, {"value": "english", "label_ar": "إنجليزي", "label_en": "English"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'specialCase', 'select', 'حالة خاصة', 'Special Case', 'اختر الحالة', 'Select case', false, 10, true, '[{"value": "", "label_ar": "لا توجد", "label_en": "None"}, {"value": "mobility", "label_ar": "إعاقة حركية", "label_en": "Mobility Disability"}, {"value": "hearing", "label_ar": "إعاقة سمعية", "label_en": "Hearing Disability"}, {"value": "visual", "label_ar": "إعاقة بصرية", "label_en": "Visual Disability"}, {"value": "learning", "label_ar": "صعوبة تعلم", "label_en": "Learning Difficulty"}, {"value": "attention", "label_ar": "تشتت انتباه", "label_en": "Attention Deficit"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'specialCaseDescription', 'textarea', 'وصف الحالة الخاصة', 'Special Case Description', 'اذكر وصف الحالة', 'Describe the case', false, 11, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'mobileNumber', 'tel', 'رقم الجوال', 'Mobile Number', '05xxxxxxxx', '05xxxxxxxx', true, 12, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'addressRegion', 'select', 'المنطقة', 'Region', 'اختر المنطقة', 'Select region', true, 13, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'addressCity', 'select', 'المدينة', 'City', 'اختر المدينة', 'Select city', true, 14, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'addressDistrict', 'select', 'الحي', 'District', 'اختر الحي', 'Select district', false, 15, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step1', 'بيانات المتقدم', 'Applicant Information', 'addressLandmark', 'text', 'أقرب معلم', 'Nearest Landmark', 'أدخل أقرب معلم', 'Enter nearest landmark', true, 16, true, NULL);

-- Step 2: معلومات ولي الأمر
INSERT INTO service_fields (service_id, service_type_id, step_id, step_title_ar, step_title_en, field_name, field_type, label_ar, label_en, placeholder_ar, placeholder_en, is_required, order_index, is_active) VALUES
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step2', 'معلومات ولي الأمر', 'Guardian Information', 'guardianName', 'text', 'اسم ولي الأمر', 'Guardian Name', 'أدخل اسم ولي الأمر', 'Enter guardian name', true, 17, true),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step2', 'معلومات ولي الأمر', 'Guardian Information', 'guardianPhone', 'tel', 'رقم هاتف ولي الأمر', 'Guardian Phone', '05xxxxxxxx', '05xxxxxxxx', true, 18, true),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'step2', 'معلومات ولي الأمر', 'Guardian Information', 'guardianWorkplace', 'text', 'مكان العمل', 'Workplace', 'أدخل مكان العمل', 'Enter workplace', true, 19, true);

-- Step 3: المستندات المطلوبة
INSERT INTO service_documents (service_id, service_type_id, document_name_ar, document_name_en, description_ar, description_en, is_required, max_size_mb, accepted_formats, order_index, is_active) VALUES
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'شهادة الأساس أو ما يعادلها', 'Basic Certificate or Equivalent', 'شهادة الأساس أو ما يعادلها مرّ عليها ثلاث سنوات', 'Basic certificate or equivalent (three years old)', true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 1, true),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'صورة شخصية حديثة', 'Recent Personal Photo', 'صورة شخصية حديثة بمقاس صورة الجواز (4×6 سم)', 'Recent passport-size photo (4×6 cm)', true, 2, '["jpg","jpeg","png"]'::jsonb, 2, true),
((SELECT id FROM services WHERE slug = 'education'), 'a1dfd5bc-0433-4eed-820c-c6babe3cd544', 'الرقم الوطني / الجواز', 'National ID / Passport', 'السودانيون: إرفاق صورة الرقم الوطني | غير السودانيين: إرفاق صورة جواز السفر', 'Sudanese: National ID copy | Non-Sudanese: Passport copy', true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 3, true);

-- ============================================
-- إضافة حقول الشهادة الثانوية
-- ============================================
-- Step 1: بيانات المتقدم
INSERT INTO service_fields (service_id, service_type_id, step_id, step_title_ar, step_title_en, field_name, field_type, label_ar, label_en, placeholder_ar, placeholder_en, is_required, order_index, is_active, options) VALUES
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'gender', 'radio', 'النوع', 'Gender', '', '', true, 1, true, '[{"value": "male", "label_ar": "ذكر", "label_en": "Male"}, {"value": "female", "label_ar": "أنثى", "label_en": "Female"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'nationality', 'radio', 'الجنسية', 'Nationality', '', '', true, 2, true, '[{"value": "sudanese", "label_ar": "سوداني", "label_en": "Sudanese"}, {"value": "non-sudanese", "label_ar": "غير سوداني", "label_en": "Non-Sudanese"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'specificNationality', 'text', 'نوع الجنسية', 'Specific Nationality', 'أدخل الجنسية', 'Enter nationality', false, 3, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'fullName', 'text', 'الاسم الرباعي مطابقاً للرقم الوطني', 'Full Name as per National ID', 'أدخل الاسم الرباعي', 'Enter full name', true, 4, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'nationalId', 'text', 'الرقم الوطني / رقم الجواز', 'National ID / Passport Number', 'أدخل الرقم الوطني أو الجواز', 'Enter ID or passport', true, 5, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'dateOfBirth', 'date', 'تاريخ الميلاد', 'Date of Birth', '', '', true, 6, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'motherName', 'text', 'اسم الأم رباعي', 'Mother Full Name', 'أدخل اسم الأم الرباعي', 'Enter mother full name', true, 7, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'qualificationType', 'select', 'نوع المؤهل', 'Qualification Type', 'اختر نوع المؤهل', 'Select qualification', true, 8, true, '[{"value": "basic", "label_ar": "أساس", "label_en": "Basic"}, {"value": "intermediate", "label_ar": "متوسطة", "label_en": "Intermediate"}, {"value": "secondary", "label_ar": "ثانوي", "label_en": "Secondary"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'schoolName', 'text', 'المدرسة', 'School Name', 'أدخل اسم المدرسة', 'Enter school name', true, 9, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'year', 'text', 'العام', 'Year', 'أدخل العام', 'Enter year', true, 10, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'priorSeatNumber', 'text', 'رقم الجلوس الذي جلست به للمؤهل', 'Prior Seat Number', 'أدخل رقم الجلوس', 'Enter seat number', false, 11, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'examLanguage', 'radio', 'لغة الامتحان', 'Exam Language', '', '', true, 12, true, '[{"value": "arabic", "label_ar": "عربي", "label_en": "Arabic"}, {"value": "english", "label_ar": "إنجليزي", "label_en": "English"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'specialCase', 'select', 'حالة خاصة', 'Special Case', 'اختر الحالة', 'Select case', false, 13, true, '[{"value": "", "label_ar": "لا توجد", "label_en": "None"}, {"value": "mobility", "label_ar": "إعاقة حركية", "label_en": "Mobility Disability"}, {"value": "hearing", "label_ar": "إعاقة سمعية", "label_en": "Hearing Disability"}, {"value": "visual", "label_ar": "إعاقة بصرية", "label_en": "Visual Disability"}, {"value": "learning", "label_ar": "صعوبة تعلم", "label_en": "Learning Difficulty"}, {"value": "attention", "label_ar": "تشتت انتباه", "label_en": "Attention Deficit"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'specialCaseDescription', 'textarea', 'وصف الحالة الخاصة', 'Special Case Description', 'اذكر وصف الحالة', 'Describe the case', false, 14, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'mobileNumber', 'tel', 'رقم هاتف جوال', 'Mobile Number', '05xxxxxxxx', '05xxxxxxxx', true, 15, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'addressRegion', 'select', 'المنطقة', 'Region', 'اختر المنطقة', 'Select region', true, 16, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'addressCity', 'select', 'المدينة', 'City', 'اختر المدينة', 'Select city', true, 17, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'addressDistrict', 'select', 'الحي', 'District', 'اختر الحي', 'Select district', false, 18, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step1', 'بيانات المتقدم', 'Applicant Information', 'addressLandmark', 'text', 'أقرب معلم', 'Nearest Landmark', 'أدخل أقرب معلم', 'Enter nearest landmark', true, 19, true, NULL);

-- Step 2: معلومات ولي الأمر
INSERT INTO service_fields (service_id, service_type_id, step_id, step_title_ar, step_title_en, field_name, field_type, label_ar, label_en, placeholder_ar, placeholder_en, is_required, order_index, is_active, options) VALUES
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step2', 'معلومات ولي الأمر', 'Guardian Information', 'guardianRelation', 'select', 'صلة القرابة', 'Relation', 'اختر صلة القرابة', 'Select relation', true, 20, true, '[{"value": "father", "label_ar": "والد", "label_en": "Father"}, {"value": "mother", "label_ar": "والدة", "label_en": "Mother"}, {"value": "guardian", "label_ar": "ولي أمر", "label_en": "Guardian"}, {"value": "other", "label_ar": "أخرى", "label_en": "Other"}]'::jsonb),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step2', 'معلومات ولي الأمر', 'Guardian Information', 'guardianPhone', 'tel', 'رقم الهاتف', 'Phone Number', '05xxxxxxxx', '05xxxxxxxx', true, 21, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step2', 'معلومات ولي الأمر', 'Guardian Information', 'guardianWorkplace', 'text', 'مكان العمل', 'Workplace', 'أدخل مكان العمل', 'Enter workplace', true, 22, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step2', 'معلومات ولي الأمر', 'Guardian Information', 'referencePerson', 'text', 'اسم شخص للرجوع إليه', 'Reference Person Name', 'أدخل الاسم', 'Enter name', true, 23, true, NULL),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step2', 'معلومات ولي الأمر', 'Guardian Information', 'referencePhone', 'tel', 'رقم هاتف الشخص للرجوع إليه', 'Reference Phone', '05xxxxxxxx', '05xxxxxxxx', true, 24, true, NULL);

-- Step 3: اختيار المواد
INSERT INTO service_fields (service_id, service_type_id, step_id, step_title_ar, step_title_en, field_name, field_type, label_ar, label_en, placeholder_ar, placeholder_en, help_text_ar, help_text_en, is_required, order_index, is_active, options) VALUES
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'step3', 'اختيار المواد', 'Subject Selection', 'electiveSubject', 'radio', 'المادة الاختيارية', 'Elective Subject', '', '', 'الاختيار لمادة واحدة فقط', 'Choose only one subject', true, 25, true, '[{"value": "biology", "label_ar": "الأحياء", "label_en": "Biology"}, {"value": "computer", "label_ar": "علوم الحاسوب", "label_en": "Computer Science"}, {"value": "engineering", "label_ar": "العلوم الهندسية", "label_en": "Engineering"}, {"value": "arts_design", "label_ar": "الفنون والتصميم", "label_en": "Arts & Design"}, {"value": "islamic_studies", "label_ar": "الدراسات الإسلامية", "label_en": "Islamic Studies"}, {"value": "english_literature", "label_ar": "الأدب الإنجليزي", "label_en": "English Literature"}, {"value": "french", "label_ar": "اللغة الفرنسية", "label_en": "French"}]'::jsonb);

-- Step 4: المستندات المطلوبة  
INSERT INTO service_documents (service_id, service_type_id, document_name_ar, document_name_en, description_ar, description_en, is_required, max_size_mb, accepted_formats, order_index, is_active) VALUES
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'الشهادة المتوسطة أو ما يعادلها', 'Intermediate Certificate or Equivalent', 'الشهادة المتوسطة أو ما يعادلها مرّ عليها ثلاث سنوات', 'Intermediate certificate or equivalent (three years old)', true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 1, true),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'الشهادة الثانوية (للمعيدين)', 'Secondary Certificate (For Repeaters)', 'الشهادة الثانوية لمن سبق له الجلوس للامتحان', 'Secondary certificate for those who previously sat for the exam', false, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 2, true),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'صورة شخصية حديثة', 'Recent Personal Photo', 'صورة شخصية حديثة بمقاس صورة الجواز (4×6 سم)', 'Recent passport-size photo (4×6 cm)', true, 2, '["jpg","jpeg","png"]'::jsonb, 3, true),
((SELECT id FROM services WHERE slug = 'education'), '0af651bf-9c46-44ab-9029-1aae46fc2224', 'الرقم الوطني / الجواز', 'National ID / Passport', 'السودانيون: إرفاق صورة الرقم الوطني | غير السودانيين: إرفاق صورة جواز السفر', 'Sudanese: National ID copy | Non-Sudanese: Passport copy', true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 4, true);

-- التحقق من الإضافة
SELECT 
  st.name_ar,
  (SELECT COUNT(*) FROM service_fields WHERE service_type_id = st.id) as fields_count,
  (SELECT COUNT(*) FROM service_documents WHERE service_type_id = st.id) as documents_count
FROM service_types st
WHERE st.service_id = (SELECT id FROM services WHERE slug = 'education')
ORDER BY st.created_at;
