

-- إدراج الخدمة
INSERT INTO services (
    name_ar, name_en, slug, description_ar, description_en,
    icon, category, fees, duration, is_active, config
  ) VALUES (
    'السجل المدني',
    NULL,
    'civilRegistry',
    'خدمات السجل المدني والأحوال الشخصية',
    NULL,
    'Users',
    'documents',
    '{"base":80,"currency":"ريال سعودي"}',
    '2-3 أيام عمل',
    TRUE,
    '{"process":["تحديد نوع الخدمة المطلوبة","تقديم المستندات المطلوبة","مراجعة البيانات","دفع الرسوم","إصدار الوثيقة"],"hasSubcategories":false,"subcategories":[]}'::jsonb
  )
  ON CONFLICT (slug)
  DO UPDATE SET
    name_ar = EXCLUDED.name_ar,
    description_ar = EXCLUDED.description_ar,
    fees = EXCLUDED.fees,
    duration = EXCLUDED.duration,
    config = EXCLUDED.config,
    updated_at = NOW();


-- حذف البيانات القديمة للخدمة
DO $$
DECLARE
  service_uuid uuid;
BEGIN
  SELECT id INTO service_uuid FROM services WHERE slug = 'civilRegistry';

  IF service_uuid IS NOT NULL THEN
    DELETE FROM service_dynamic_list_fields
    WHERE parent_field_id IN (SELECT id FROM service_fields WHERE service_id = service_uuid);

    DELETE FROM service_requirements WHERE service_id = service_uuid;
    DELETE FROM service_documents WHERE service_id = service_uuid;
    DELETE FROM service_fields WHERE service_id = service_uuid;
  END IF;
END $$;


-- إدراج المتطلبات
INSERT INTO service_requirements (service_id, requirement_ar, requirement_en, order_index, is_active, conditions)
SELECT id, * FROM services, (VALUES
  ('صورة من الرقم الوطني أو الجواز', NULL, 0, TRUE, '{"type":"national_id_replacement"}'::jsonb),
  ('صورة حديثة', NULL, 1, TRUE, '{"type":"national_id_replacement"}'::jsonb),
  ('صورة من الجواز أو الرقم الوطني للوالد والوالدة', NULL, 2, TRUE, '{"type":"national_id_newborn"}'::jsonb),
  ('شهادة ميلاد أو تبليغ ولادة معتمد', NULL, 3, TRUE, '{"type":"national_id_newborn"}'::jsonb),
  ('قسيمة الزواج', NULL, 4, TRUE, '{"type":"national_id_newborn"}'::jsonb),
  ('صورة فوتوغرافية حديثة للطفل', NULL, 5, TRUE, '{"type":"national_id_newborn"}'::jsonb),
  ('حضور الوالد والطفل', NULL, 6, TRUE, '{"type":"national_id_newborn"}'::jsonb),
  ('الحضور المباشر للقنصلية بعد تأكيد الموعد', NULL, 7, TRUE, '{"type":"national_id_under12"}'::jsonb),
  ('شاهد من العصب', NULL, 8, TRUE, '{"type":"national_id_under12"}'::jsonb),
  ('شهادة ميلاد', NULL, 9, TRUE, '{"type":"national_id_under12"}'::jsonb),
  ('عدد 2 صورة فوتوغرافية', NULL, 10, TRUE, '{"type":"national_id_under12"}'::jsonb),
  ('صورة من الرقم الوطني', NULL, 11, TRUE, '{"type":"name_correction"}'::jsonb),
  ('شهادة الميلاد', NULL, 12, TRUE, '{"type":"name_correction"}'::jsonb),
  ('صورة من الجواز', NULL, 13, TRUE, '{"type":"name_correction"}'::jsonb),
  ('إشهاد شرعي', NULL, 14, TRUE, '{"type":"name_correction"}'::jsonb),
  ('نشر الجريدة الرسمية', NULL, 15, TRUE, '{"type":"name_correction"}'::jsonb),
  ('إفادة قوائم الحظر والسيطرة', NULL, 16, TRUE, '{"type":"name_correction"}'::jsonb),
  ('إفادة من الإنتربول', NULL, 17, TRUE, '{"type":"name_correction"}'::jsonb),
  ('كتابة طلب لتوضيح الأسباب بخط اليد', NULL, 18, TRUE, '{"type":"name_correction"}'::jsonb),
  ('صورة حديثة', NULL, 19, TRUE, '{"type":"name_correction"}'::jsonb),
  ('صورة من الرقم الوطني', NULL, 20, TRUE, '{"type":"age_correction"}'::jsonb),
  ('شهادة الميلاد', NULL, 21, TRUE, '{"type":"age_correction"}'::jsonb),
  ('صورة من الجواز', NULL, 22, TRUE, '{"type":"age_correction"}'::jsonb),
  ('كتابة طلب لتوضيح الأسباب بخط اليد', NULL, 23, TRUE, '{"type":"age_correction"}'::jsonb),
  ('مستندات داعمة ذات صلة', NULL, 24, TRUE, '{"type":"age_correction"}'::jsonb),
  ('صورة حديثة', NULL, 25, TRUE, '{"type":"age_correction"}'::jsonb),
  ('صورة من الجواز', NULL, 26, TRUE, '{"type":"conduct_certificate"}'::jsonb),
  ('عدد 2 صورة بطاقة', NULL, 27, TRUE, '{"type":"conduct_certificate"}'::jsonb),
  ('الحضور للقنصلية للبصمة', NULL, 28, TRUE, '{"type":"conduct_certificate"}'::jsonb),
  ('صورة من الجواز', NULL, 29, TRUE, '{"type":"towhomitmayconcern"}'::jsonb)
) AS req(requirement_ar, requirement_en, order_index, is_active, conditions)
WHERE services.slug = 'civilRegistry';

-- إدراج الحقول
INSERT INTO service_fields (
  service_id, step_id, step_title_ar, step_title_en, field_name, field_type,
  label_ar, label_en, placeholder_ar, placeholder_en, help_text_ar, help_text_en,
  default_value, is_required, validation_rules, options, order_index, is_active, conditions
)
SELECT id, * FROM services, (VALUES
  ('service-details', 'تفاصيل الخدمة', NULL, 'recordType', 'select',
   'نوع السجل', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"نوع السجل مطلوب"}'::jsonb, '[{"value":"national_id","label":"الرقم الوطني"},{"value":"conduct_certificate","label":"شهادة حسن السير والسلوك (الفيش)"},{"value":"towhomitmayconcern","label":"إفادات لمن يهمهم الأمر"}]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'idType', 'radio',
   'نوع الخدمة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"نوع الخدمة مطلوب"}'::jsonb, '[{"value":"replacement","label":"بدل فاقد","description":"الرقم الوطني بدل فاقد"},{"value":"newborn","label":"رقم وطني للأطفال حديثي الولادة حتى 12 سنة","description":"للأطفال من الولادة حتى 12 سنة"},{"value":"under12","label":"رقم وطني لمن دون سن 12 عام","description":"للأطفال دون 12 عام (حالات خاصة)"},{"value":"name_correction","label":"تعديل الاسم أو تغييره","description":"في حالة الأخطاء"},{"value":"age_correction","label":"تعديل العمر","description":"حالة خاصة - زيادة أو نقصان"}]'::jsonb, 1, TRUE, '{"field":"recordType","values":["national_id"]}'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'nationalId', 'text',
   'اكتب الرقم الوطني', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"الرقم الوطني مطلوب"}'::jsonb, '[]'::jsonb, 2, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["replacement","name_correction","age_correction"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'motherFullName', 'text',
   'اسم الأم رباعي', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"اسم الأم رباعي مطلوب"}'::jsonb, '[]'::jsonb, 3, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["replacement","newborn","under12","name_correction","age_correction"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'birthDate', 'date',
   'تاريخ الميلاد', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"تاريخ الميلاد مطلوب"}'::jsonb, '[]'::jsonb, 4, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["replacement","newborn","under12","name_correction"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'childGender', 'radio',
   'نوع المولود', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"نوع المولود مطلوب"}'::jsonb, '[{"value":"male","label":"ذكر"},{"value":"female","label":"أنثى"}]'::jsonb, 5, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["newborn","under12"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'childFullNameArabic', 'text',
   'اسم الطفل رباعي', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"اسم الطفل رباعي مطلوب"}'::jsonb, '[]'::jsonb, 6, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["newborn","under12"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'childFullNameEnglish', 'text',
   'Child''s Full Name (Four Parts)', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"Child''s full name in English is required"}'::jsonb, '[]'::jsonb, 7, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["newborn","under12"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'bloodType', 'select',
   'فصيلة الدم', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"فصيلة الدم مطلوبة"}'::jsonb, '[{"value":"A+","label":"A+"},{"value":"A-","label":"A-"},{"value":"B+","label":"B+"},{"value":"B-","label":"B-"},{"value":"AB+","label":"AB+"},{"value":"AB-","label":"AB-"},{"value":"O+","label":"O+"},{"value":"O-","label":"O-"}]'::jsonb, 8, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["newborn","under12"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'birthRegion', 'text',
   'مكان الميلاد - المنطقة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"المنطقة مطلوبة"}'::jsonb, '[]'::jsonb, 9, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["newborn","under12"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'birthCity', 'text',
   'مكان الميلاد - المدينة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"المدينة مطلوبة"}'::jsonb, '[]'::jsonb, 10, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["newborn","under12"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'birthHospital', 'text',
   'مكان الميلاد - المستشفى', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"المستشفى مطلوب"}'::jsonb, '[]'::jsonb, 11, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["newborn","under12"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'fatherAttending', 'radio',
   'هل سيحضر الوالد؟', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"يرجى تحديد حضور الوالد"}'::jsonb, '[{"value":"yes","label":"نعم"},{"value":"no","label":"لا - سيحضر شهود"}]'::jsonb, 12, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'witness1Name', 'text',
   'اسم الشاهد الأول', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"اسم الشاهد الأول مطلوب"}'::jsonb, '[]'::jsonb, 13, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]},{"field":"fatherAttending","values":["no"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'witness1PassportNumber', 'text',
   'رقم جواز الشاهد الأول', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم الجواز مطلوب"}'::jsonb, '[]'::jsonb, 14, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]},{"field":"fatherAttending","values":["no"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'witness1Relation', 'select',
   'صلة القرابة للشاهد الأول', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صلة القرابة مطلوبة"}'::jsonb, '[{"value":"uncle_paternal","label":"عم"},{"value":"brother","label":"أخ شقيق"}]'::jsonb, 15, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]},{"field":"fatherAttending","values":["no"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'witness1Phone', 'tel',
   'رقم هاتف الشاهد الأول', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم الهاتف مطلوب"}'::jsonb, '[]'::jsonb, 16, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]},{"field":"fatherAttending","values":["no"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'witness2Name', 'text',
   'اسم الشاهد الثاني', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"اسم الشاهد الثاني مطلوب"}'::jsonb, '[]'::jsonb, 17, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]},{"field":"fatherAttending","values":["no"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'witness2PassportNumber', 'text',
   'رقم جواز الشاهد الثاني', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم الجواز مطلوب"}'::jsonb, '[]'::jsonb, 18, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]},{"field":"fatherAttending","values":["no"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'witness2Relation', 'select',
   'صلة القرابة للشاهد الثاني', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صلة القرابة مطلوبة"}'::jsonb, '[{"value":"uncle_paternal","label":"عم"},{"value":"brother","label":"أخ شقيق"}]'::jsonb, 19, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]},{"field":"fatherAttending","values":["no"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'witness2Phone', 'tel',
   'رقم هاتف الشاهد الثاني', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم الهاتف مطلوب"}'::jsonb, '[]'::jsonb, 20, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]},{"field":"fatherAttending","values":["no"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'correctedName', 'text',
   'الاسم المعدل', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"الاسم المعدل مطلوب"}'::jsonb, '[]'::jsonb, 21, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'nameCorrectionReason', 'textarea',
   'وضح أسباب التعديل', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"أسباب التعديل مطلوبة"}'::jsonb, '[]'::jsonb, 22, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'wrongBirthDate', 'date',
   'تاريخ الميلاد الخطأ', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"تاريخ الميلاد الخطأ مطلوب"}'::jsonb, '[]'::jsonb, 23, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["age_correction"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'correctBirthDate', 'date',
   'تاريخ الميلاد الصحيح', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"تاريخ الميلاد الصحيح مطلوب"}'::jsonb, '[]'::jsonb, 24, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["age_correction"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'ageCorrectionReason', 'textarea',
   'وضح أسباب التعديل', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"أسباب التعديل مطلوبة"}'::jsonb, '[]'::jsonb, 25, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["age_correction"]}]}]'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'nationalNumber', 'text',
   'الرقم الوطني', NULL, NULL, NULL, 'أدخل الرقم الوطني', NULL, NULL,
   true, '{"required":"الرقم الوطني مطلوب"}'::jsonb, '[]'::jsonb, 26, TRUE, '{"field":"recordType","values":["conduct_certificate"]}'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'motherFullName', 'text',
   'اسم الأم رباعي', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"اسم الأم رباعي مطلوب"}'::jsonb, '[]'::jsonb, 27, TRUE, '{"field":"recordType","values":["conduct_certificate"]}'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'requestingAuthority', 'text',
   'الجهة الطالبة للفيش', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"الجهة الطالبة مطلوبة"}'::jsonb, '[]'::jsonb, 28, TRUE, '{"field":"recordType","values":["conduct_certificate"]}'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'requestReason', 'select',
   'سبب طلب الفيش', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"سبب الطلب مطلوب"}'::jsonb, '[{"value":"work","label":"للعمل"},{"value":"study","label":"للدراسة"},{"value":"travel","label":"للسفر"},{"value":"residence","label":"للإقامة"},{"value":"marriage","label":"للزواج"},{"value":"government","label":"للجهات الحكومية"},{"value":"other","label":"أخرى"}]'::jsonb, 29, TRUE, '{"field":"recordType","values":["conduct_certificate"]}'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'concernSubject', 'text',
   'الموضوع', NULL, NULL, NULL, 'عنوان أو موضوع الإفادة', NULL, NULL,
   true, '{"required":"الموضوع مطلوب"}'::jsonb, '[]'::jsonb, 30, TRUE, '{"field":"recordType","values":["towhomitmayconcern"]}'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'civilRegistryData', 'textarea',
   'بيانات السجل المدني', NULL, NULL, NULL, 'أدخل بياناتك من السجل المدني (الاسم الرباعي، الرقم الوطني، تاريخ الميلاد، مكان الميلاد، إلخ)', NULL, NULL,
   true, '{"required":"بيانات السجل المدني مطلوبة"}'::jsonb, '[]'::jsonb, 31, TRUE, '{"field":"recordType","values":["towhomitmayconcern"]}'::jsonb),
  ('service-details', 'تفاصيل الخدمة', NULL, 'requestExplanation', 'textarea',
   'شرح الطلب', NULL, NULL, NULL, 'اشرح تفاصيل الطلب والغرض من الإفادة والمعلومات المطلوب إثباتها', NULL, NULL,
   true, '{"required":"شرح الطلب مطلوب"}'::jsonb, '[]'::jsonb, 32, TRUE, '{"field":"recordType","values":["towhomitmayconcern"]}'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'replacementIdOrPassport', 'file',
   'صورة من الرقم الوطني أو الجواز', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة من الرقم الوطني أو الجواز مطلوبة"}'::jsonb, '[]'::jsonb, 0, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["replacement"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'replacementPhoto', 'file',
   'صورة حديثة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"الصورة الحديثة مطلوبة"}'::jsonb, '[]'::jsonb, 1, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["replacement"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'newbornFatherIdOrPassport', 'file',
   'صورة من الجواز أو الرقم الوطني للوالد', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة من الجواز أو الرقم الوطني للوالد مطلوبة"}'::jsonb, '[]'::jsonb, 2, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["newborn"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'newbornMotherIdOrPassport', 'file',
   'صورة من الجواز أو الرقم الوطني للوالدة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة من الجواز أو الرقم الوطني للوالدة مطلوبة"}'::jsonb, '[]'::jsonb, 3, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["newborn"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'newbornBirthCertificate', 'file',
   'شهادة ميلاد أو تبليغ ولادة معتمد (للأطفال تحت 90 يوم)', NULL, NULL, NULL, 'شهادة ميلاد أو تبليغ ولادة معتمد من دولة التمثيل في حالة الطفل لا يتجاوز 90 يوم', NULL, NULL,
   true, '{"required":"شهادة الميلاد أو تبليغ الولادة مطلوبة"}'::jsonb, '[]'::jsonb, 4, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["newborn"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'newbornMarriageCertificate', 'file',
   'قسيمة الزواج', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"قسيمة الزواج مطلوبة"}'::jsonb, '[]'::jsonb, 5, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["newborn"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'newbornChildPhoto', 'file',
   'صورة فوتوغرافية حديثة للطفل', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة الطفل مطلوبة"}'::jsonb, '[]'::jsonb, 6, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["newborn"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'under12FatherIdOrPassport', 'file',
   'صورة من الجواز أو الرقم الوطني للوالد', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة من الجواز أو الرقم الوطني للوالد مطلوبة"}'::jsonb, '[]'::jsonb, 7, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'under12MotherIdOrPassport', 'file',
   'صورة من الجواز أو الرقم الوطني للوالدة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة من الجواز أو الرقم الوطني للوالدة مطلوبة"}'::jsonb, '[]'::jsonb, 8, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'under12BirthCertificate', 'file',
   'شهادة الميلاد', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"شهادة الميلاد مطلوبة"}'::jsonb, '[]'::jsonb, 9, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'under12MarriageCertificate', 'file',
   'قسيمة الزواج', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"قسيمة الزواج مطلوبة"}'::jsonb, '[]'::jsonb, 10, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'under12Photo', 'file',
   'صورة فوتوغرافية حديثة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"الصورة الفوتوغرافية مطلوبة"}'::jsonb, '[]'::jsonb, 11, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'witness1Passport', 'file',
   'صورة جواز الشاهد الأول', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة جواز الشاهد الأول مطلوبة"}'::jsonb, '[]'::jsonb, 12, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]},{"field":"fatherAttending","values":["no"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'witness2Passport', 'file',
   'صورة جواز الشاهد الثاني', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة جواز الشاهد الثاني مطلوبة"}'::jsonb, '[]'::jsonb, 13, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]},{"field":"fatherAttending","values":["no"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'nameCorrectionNationalId', 'file',
   'صورة من الرقم الوطني', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة الرقم الوطني مطلوبة"}'::jsonb, '[]'::jsonb, 14, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'nameCorrectionBirthCertificate', 'file',
   'شهادة الميلاد', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"شهادة الميلاد مطلوبة"}'::jsonb, '[]'::jsonb, 15, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'nameCorrectionPassport', 'file',
   'صورة من الجواز', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة الجواز مطلوبة"}'::jsonb, '[]'::jsonb, 16, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'nameCorrectionLegalAffidavit', 'file',
   'إشهاد شرعي', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"الإشهاد الشرعي مطلوب"}'::jsonb, '[]'::jsonb, 17, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'nameCorrectionGazettePublication', 'file',
   'نشر الجريدة الرسمية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"نشر الجريدة الرسمية مطلوب"}'::jsonb, '[]'::jsonb, 18, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'nameCorrectionSanctionsClearance', 'file',
   'إفادة قوائم الحظر والسيطرة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"إفادة قوائم الحظر والسيطرة مطلوبة"}'::jsonb, '[]'::jsonb, 19, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'nameCorrectionInterpolClearance', 'file',
   'إفادة من الإنتربول', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"إفادة من الإنتربول مطلوبة"}'::jsonb, '[]'::jsonb, 20, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'nameCorrectionHandwrittenRequest', 'file',
   'كتابة طلب لتوضيح الأسباب بخط اليد', NULL, NULL, NULL, 'يجب أن يكون الطلب مكتوباً بخط اليد', NULL, NULL,
   true, '{"required":"الطلب المكتوب بخط اليد مطلوب"}'::jsonb, '[]'::jsonb, 21, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'nameCorrectionPhoto', 'file',
   'صورة حديثة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"الصورة الحديثة مطلوبة"}'::jsonb, '[]'::jsonb, 22, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'ageCorrectionNationalId', 'file',
   'صورة من الرقم الوطني', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة الرقم الوطني مطلوبة"}'::jsonb, '[]'::jsonb, 23, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["age_correction"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'ageCorrectionBirthCertificate', 'file',
   'شهادة الميلاد', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"شهادة الميلاد مطلوبة"}'::jsonb, '[]'::jsonb, 24, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["age_correction"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'ageCorrectionPassport', 'file',
   'صورة من الجواز', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة الجواز مطلوبة"}'::jsonb, '[]'::jsonb, 25, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["age_correction"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'ageCorrectionHandwrittenRequest', 'file',
   'كتابة طلب لتوضيح الأسباب بخط اليد', NULL, NULL, NULL, 'يجب أن يكون الطلب مكتوباً بخط اليد', NULL, NULL,
   true, '{"required":"الطلب المكتوب بخط اليد مطلوب"}'::jsonb, '[]'::jsonb, 26, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["age_correction"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'ageCorrectionSupportingDocs', 'file',
   'مستندات داعمة ذات صلة', NULL, NULL, NULL, 'أي مستندات تدعم طلب تعديل العمر', NULL, NULL,
   true, '{"required":"المستندات الداعمة مطلوبة"}'::jsonb, '[]'::jsonb, 27, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["age_correction"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'ageCorrectionPhoto', 'file',
   'صورة حديثة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"الصورة الحديثة مطلوبة"}'::jsonb, '[]'::jsonb, 28, TRUE, '[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["age_correction"]}]}]'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'conductPassportCopy', 'file',
   'صورة من الجواز', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة من الجواز مطلوبة"}'::jsonb, '[]'::jsonb, 29, TRUE, '{"field":"recordType","values":["conduct_certificate"]}'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'conductRecentPhoto', 'file',
   'صورة حديثة', NULL, NULL, NULL, 'صورة شخصية حديثة', NULL, NULL,
   true, '{"required":"صورة حديثة مطلوبة"}'::jsonb, '[]'::jsonb, 30, TRUE, '{"field":"recordType","values":["conduct_certificate"]}'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'concernPassportCopy', 'file',
   'صورة من الجواز', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة من الجواز مطلوبة"}'::jsonb, '[]'::jsonb, 31, TRUE, '{"field":"recordType","values":["towhomitmayconcern"]}'::jsonb),
  ('documents-upload', 'المستندات المطلوبة', NULL, 'concernRelatedFiles', 'file',
   'ملفات ذات صلة (إن وجدت)', NULL, NULL, NULL, 'أي ملفات أو مستندات ذات صلة بالطلب (اختياري)', NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 32, TRUE, '{"field":"recordType","values":["towhomitmayconcern"]}'::jsonb)
) AS fld(
  step_id, step_title_ar, step_title_en, field_name, field_type, label_ar, label_en,
  placeholder_ar, placeholder_en, help_text_ar, help_text_en, default_value,
  is_required, validation_rules, options, order_index, is_active, conditions
)
WHERE services.slug = 'civilRegistry';

-- إدراج المرفقات
INSERT INTO service_documents (
  service_id, document_name_ar, document_name_en, description_ar, description_en,
  is_required, max_size_mb, accepted_formats, order_index, is_active, conditions
)
SELECT id, * FROM services, (VALUES
  ('صورة من الرقم الوطني أو الجواز', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 0, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["replacement"]}]}]}'::jsonb),
  ('صورة حديثة', NULL, NULL, NULL,
   true, 2, '["jpg","jpeg","png"]'::jsonb, 1, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["replacement"]}]}]}'::jsonb),
  ('صورة من الجواز أو الرقم الوطني للوالد', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 2, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["newborn"]}]}]}'::jsonb),
  ('صورة من الجواز أو الرقم الوطني للوالدة', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 3, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["newborn"]}]}]}'::jsonb),
  ('شهادة ميلاد أو تبليغ ولادة معتمد (للأطفال تحت 90 يوم)', NULL, 'شهادة ميلاد أو تبليغ ولادة معتمد من دولة التمثيل في حالة الطفل لا يتجاوز 90 يوم', NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 4, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["newborn"]}]}]}'::jsonb),
  ('قسيمة الزواج', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 5, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["newborn"]}]}]}'::jsonb),
  ('صورة فوتوغرافية حديثة للطفل', NULL, NULL, NULL,
   true, 2, '["jpg","jpeg","png"]'::jsonb, 6, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["newborn"]}]}]}'::jsonb),
  ('صورة من الجواز أو الرقم الوطني للوالد', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 7, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]}]}]}'::jsonb),
  ('صورة من الجواز أو الرقم الوطني للوالدة', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 8, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]}]}]}'::jsonb),
  ('شهادة الميلاد', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 9, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]}]}]}'::jsonb),
  ('قسيمة الزواج', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 10, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]}]}]}'::jsonb),
  ('صورة فوتوغرافية حديثة', NULL, NULL, NULL,
   true, 2, '["jpg","jpeg","png"]'::jsonb, 11, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]}]}]}'::jsonb),
  ('صورة جواز الشاهد الأول', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 12, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]},{"field":"fatherAttending","values":["no"]}]}]}'::jsonb),
  ('صورة جواز الشاهد الثاني', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 13, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["under12"]},{"field":"fatherAttending","values":["no"]}]}]}'::jsonb),
  ('صورة من الرقم الوطني', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 14, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]}'::jsonb),
  ('شهادة الميلاد', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 15, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]}'::jsonb),
  ('صورة من الجواز', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 16, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]}'::jsonb),
  ('إشهاد شرعي', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 17, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]}'::jsonb),
  ('نشر الجريدة الرسمية', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 18, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]}'::jsonb),
  ('إفادة قوائم الحظر والسيطرة', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 19, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]}'::jsonb),
  ('إفادة من الإنتربول', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 20, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]}'::jsonb),
  ('كتابة طلب لتوضيح الأسباب بخط اليد', NULL, 'يجب أن يكون الطلب مكتوباً بخط اليد', NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 21, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]}'::jsonb),
  ('صورة حديثة', NULL, NULL, NULL,
   true, 2, '["jpg","jpeg","png"]'::jsonb, 22, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["name_correction"]}]}]}'::jsonb),
  ('صورة من الرقم الوطني', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 23, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["age_correction"]}]}]}'::jsonb),
  ('شهادة الميلاد', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 24, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["age_correction"]}]}]}'::jsonb),
  ('صورة من الجواز', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 25, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["age_correction"]}]}]}'::jsonb),
  ('كتابة طلب لتوضيح الأسباب بخط اليد', NULL, 'يجب أن يكون الطلب مكتوباً بخط اليد', NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 26, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["age_correction"]}]}]}'::jsonb),
  ('مستندات داعمة ذات صلة', NULL, 'أي مستندات تدعم طلب تعديل العمر', NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 27, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["age_correction"]}]}]}'::jsonb),
  ('صورة حديثة', NULL, NULL, NULL,
   true, 2, '["jpg","jpeg","png"]'::jsonb, 28, TRUE, '{"show_when":[{"operator":"AND","conditions":[{"field":"recordType","values":["national_id"]},{"field":"idType","values":["age_correction"]}]}]}'::jsonb),
  ('صورة من الجواز', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 29, TRUE, '{"show_when":[{"operator":"OR","conditions":[{"field":"recordType","operator":"equals","value":["conduct_certificate"]}]}]}'::jsonb),
  ('صورة حديثة', NULL, 'صورة شخصية حديثة', NULL,
   true, 5, '["jpg","jpeg","png"]'::jsonb, 30, TRUE, '{"show_when":[{"operator":"OR","conditions":[{"field":"recordType","operator":"equals","value":["conduct_certificate"]}]}]}'::jsonb),
  ('صورة من الجواز', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 31, TRUE, '{"show_when":[{"operator":"OR","conditions":[{"field":"recordType","operator":"equals","value":["towhomitmayconcern"]}]}]}'::jsonb),
  ('ملفات ذات صلة (إن وجدت)', NULL, 'أي ملفات أو مستندات ذات صلة بالطلب (اختياري)', NULL,
   false, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 32, TRUE, '{"show_when":[{"operator":"OR","conditions":[{"field":"recordType","operator":"equals","value":["towhomitmayconcern"]}]}]}'::jsonb)
) AS doc(document_name_ar, document_name_en, description_ar, description_en,
  is_required, max_size_mb, accepted_formats, order_index, is_active, conditions)
WHERE services.slug = 'civilRegistry';

