

-- إدراج الخدمة
INSERT INTO services (
    name_ar, name_en, slug, description_ar, description_en,
    icon, category, fees, duration, is_active, config
  ) VALUES (
    'المأذونية',
    NULL,
    'madhoonia',
    'خدمات عقود الزواج والطلاق',
    NULL,
    'FileHeart',
    'consular',
    '{"marriage":210,"divorce":100,"currency":"ريال سعودي"}',
    'يوم واحد',
    TRUE,
    '{"process":["تحديد نوع الخدمة (زواج أو طلاق)","تعبئة نموذج الطلب","إرفاق المستندات المطلوبة","الحضور الشخصي مع الشهود","إتمام الإجراء"],"hasSubcategories":false,"subcategories":[]}'::jsonb
  )
  ON CONFLICT (slug)
  DO UPDATE SET
    name_ar = EXCLUDED.name_ar,
    description_ar = EXCLUDED.description_ar,
    fees = EXCLUDED.fees,
    duration = EXCLUDED.duration,
    config = EXCLUDED.config,
    updated_at = NOW();


-- حذف البيانات القديمة للخدمة
DO $$
DECLARE
  service_uuid uuid;
BEGIN
  SELECT id INTO service_uuid FROM services WHERE slug = 'madhoonia';

  IF service_uuid IS NOT NULL THEN
    DELETE FROM service_dynamic_list_fields
    WHERE parent_field_id IN (SELECT id FROM service_fields WHERE service_id = service_uuid);

    DELETE FROM service_requirements WHERE service_id = service_uuid;
    DELETE FROM service_documents WHERE service_id = service_uuid;
    DELETE FROM service_fields WHERE service_id = service_uuid;
  END IF;
END $$;


-- إدراج المتطلبات
INSERT INTO service_requirements (service_id, requirement_ar, requirement_en, order_index, is_active, conditions)
SELECT id, * FROM services, (VALUES
  ('إثبات الشخصية: الجواز أو الرقم الوطني (الخاطب، المخطوبة، ولي المخطوبة (الأب)، الشاهدان)', NULL, 0, TRUE, '{"type":"marriage"}'::jsonb),
  ('في حال كانت المخطوبة غائبة عن مجلس العقد: يجب احضار إقرار موافقة على الزواج', NULL, 1, TRUE, '{"type":"marriage"}'::jsonb),
  ('في حال كانت المخطوبة مطلقة: يجب إحضار أصل وثيقة الطلاق موثقة من الخارجية السودانية', NULL, 2, TRUE, '{"type":"marriage"}'::jsonb),
  ('في حال كانت المخطوبة أرملة: يجب احضار وثيقة الزواج وشهادة وفاة الزوج الأول أو الاعلام الشرعي للورثة', NULL, 3, TRUE, '{"type":"marriage"}'::jsonb),
  ('في حال غياب والد المخطوبة: يجب احضار أصل توكيل لمن ينوب عنه في الإجراءات موثق من الخارجية السودانية', NULL, 4, TRUE, '{"type":"marriage"}'::jsonb),
  ('في حال وجود الولي (والد المخطوبة) خارج السودان: يجب إحضار توكيل لمن ينوب عنه في الإجراءات صادر من السفارة السودانية بمحل إقامته', NULL, 5, TRUE, '{"type":"marriage"}'::jsonb),
  ('في حال وفاة ولي المخطوبة (الأب): يجب إبراز اثبات وفاته، أو الإعلام الشرعي للوراثة (الأصل)، وينوب عنه الولي الأقرب على ترتيب الإرث', NULL, 6, TRUE, '{"type":"marriage"}'::jsonb),
  ('القسيمة', NULL, 7, TRUE, '{"type":"divorce"}'::jsonb),
  ('صورة جواز الزوج', NULL, 8, TRUE, '{"type":"divorce"}'::jsonb),
  ('صورة جواز الزوجة', NULL, 9, TRUE, '{"type":"divorce"}'::jsonb),
  ('صورة جواز الشاهد الأول', NULL, 10, TRUE, '{"type":"divorce"}'::jsonb),
  ('صورة جواز الشاهد الثاني', NULL, 11, TRUE, '{"type":"divorce"}'::jsonb),
  ('مستندات إضافية إن وجد', NULL, 12, TRUE, '{"type":"divorce"}'::jsonb)
) AS req(requirement_ar, requirement_en, order_index, is_active, conditions)
WHERE services.slug = 'madhoonia';

-- إدراج الحقول
INSERT INTO service_fields (
  service_id, step_id, step_title_ar, step_title_en, field_name, field_type,
  label_ar, label_en, placeholder_ar, placeholder_en, help_text_ar, help_text_en,
  default_value, is_required, validation_rules, options, order_index, is_active, conditions
)
SELECT id, * FROM services, (VALUES
  ('service-details', 'تفاصيل الخدمة', NULL, 'serviceType', 'radio',
   'نوع الخدمة المطلوبة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"نوع الخدمة مطلوب"}'::jsonb, '[{"value":"marriage","label":"الزواج"},{"value":"divorce","label":"الطلاق"}]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('groom-info', 'بيانات الخاطب', NULL, 'groomFullName', 'text',
   'اسم الخاطب (رباعي)', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"اسم الخاطب مطلوب"}'::jsonb, '[]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('groom-info', 'بيانات الخاطب', NULL, 'groomBirthDate', 'date',
   'تاريخ الميلاد', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"تاريخ الميلاد مطلوب"}'::jsonb, '[]'::jsonb, 1, TRUE, '{}'::jsonb),
  ('groom-info', 'بيانات الخاطب', NULL, 'groomPassportNumber', 'text',
   'رقم جواز السفر', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم جواز السفر مطلوب"}'::jsonb, '[]'::jsonb, 2, TRUE, '{}'::jsonb),
  ('groom-info', 'بيانات الخاطب', NULL, 'groomPassportIssuePlace', 'text',
   'مكان الإصدار', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"مكان إصدار الجواز مطلوب"}'::jsonb, '[]'::jsonb, 3, TRUE, '{}'::jsonb),
  ('groom-info', 'بيانات الخاطب', NULL, 'groomPassportIssueDate', 'date',
   'تاريخ الإصدار', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"تاريخ إصدار الجواز مطلوب"}'::jsonb, '[]'::jsonb, 4, TRUE, '{}'::jsonb),
  ('groom-info', 'بيانات الخاطب', NULL, 'groomResidenceStatus', 'select',
   'حالة الإقامة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"حالة الإقامة مطلوبة"}'::jsonb, '[{"value":"resident","label":"مقيم"},{"value":"visitor","label":"زيارة"},{"value":"umrah","label":"عمرة"}]'::jsonb, 5, TRUE, '{}'::jsonb),
  ('groom-info', 'بيانات الخاطب', NULL, 'groomResidenceNumber', 'text',
   'رقم الإقامة', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 6, TRUE, '(data) => data.groomResidenceStatus === ''resident'''),
  ('groom-info', 'بيانات الخاطب', NULL, 'groomOccupation', 'text',
   'المهنة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"المهنة مطلوبة"}'::jsonb, '[]'::jsonb, 7, TRUE, '{}'::jsonb),
  ('groom-info', 'بيانات الخاطب', NULL, 'groomMaritalStatus', 'select',
   'الحالة الإجتماعية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"الحالة الإجتماعية مطلوبة"}'::jsonb, '[{"value":"single","label":"لم يسبق له الزواج"},{"value":"divorced","label":"مطلق"},{"value":"widower","label":"أرمل"},{"value":"polygamous","label":"معدد"}]'::jsonb, 8, TRUE, '{}'::jsonb),
  ('groom-info', 'بيانات الخاطب', NULL, 'groomWivesCount', 'number',
   'عدد الزوجات', NULL, NULL, NULL, 'أدخل عدد الزوجات الحاليات', NULL, NULL,
   false, '{"min":1,"max":3}'::jsonb, '[]'::jsonb, 9, TRUE, '(data) => data.groomMaritalStatus === ''polygamous'''),
  ('groom-info', 'بيانات الخاطب', NULL, 'groomAddressKSA', 'text',
   'العنوان بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"العنوان بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 10, TRUE, '{}'::jsonb),
  ('groom-info', 'بيانات الخاطب', NULL, 'groomMobileKSA', 'tel',
   'رقم الجوال بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم الجوال بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 11, TRUE, '{}'::jsonb),
  ('groom-info', 'بيانات الخاطب', NULL, 'groomAddressSudan', 'text',
   'العنوان بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 12, TRUE, '{}'::jsonb),
  ('groom-info', 'بيانات الخاطب', NULL, 'groomMobileSudan', 'tel',
   'رقم الجوال بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 13, TRUE, '{}'::jsonb),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideFullName', 'text',
   'اسم المخطوبة (رباعي)', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"اسم المخطوبة مطلوب"}'::jsonb, '[]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideBirthDate', 'date',
   'تاريخ الميلاد', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"تاريخ الميلاد مطلوب"}'::jsonb, '[]'::jsonb, 1, TRUE, '{}'::jsonb),
  ('bride-info', 'بيانات المخطوبة', NULL, 'bridePassportNumber', 'text',
   'رقم جواز السفر', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم جواز السفر مطلوب"}'::jsonb, '[]'::jsonb, 2, TRUE, '{}'::jsonb),
  ('bride-info', 'بيانات المخطوبة', NULL, 'bridePassportIssuePlace', 'text',
   'مكان الإصدار', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"مكان إصدار الجواز مطلوب"}'::jsonb, '[]'::jsonb, 3, TRUE, '{}'::jsonb),
  ('bride-info', 'بيانات المخطوبة', NULL, 'bridePassportIssueDate', 'date',
   'تاريخ الإصدار', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"تاريخ إصدار الجواز مطلوب"}'::jsonb, '[]'::jsonb, 4, TRUE, '{}'::jsonb),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideResidenceStatus', 'select',
   'حالة الإقامة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"حالة الإقامة مطلوبة"}'::jsonb, '[{"value":"resident","label":"مقيم"},{"value":"visitor","label":"زيارة"},{"value":"umrah","label":"عمرة"}]'::jsonb, 5, TRUE, '{}'::jsonb),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideResidenceNumber', 'text',
   'رقم الإقامة', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 6, TRUE, '(data) => data.brideResidenceStatus === ''resident'''),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideOccupation', 'text',
   'المهنة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"المهنة مطلوبة"}'::jsonb, '[]'::jsonb, 7, TRUE, '{}'::jsonb),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideMaritalStatus', 'select',
   'الحالة الإجتماعية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"الحالة الإجتماعية مطلوبة"}'::jsonb, '[{"value":"single","label":"لم يسبق لها الزواج"},{"value":"divorced","label":"مطلقة"},{"value":"widow","label":"أرملة"}]'::jsonb, 8, TRUE, '{}'::jsonb),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideDivorceDocNumber', 'text',
   'رقم وثيقة الطلاق', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 9, TRUE, '(data) => data.brideMaritalStatus === ''divorced'''),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideDivorceDocIssuer', 'text',
   'جهة إصدار وثيقة الطلاق', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 10, TRUE, '(data) => data.brideMaritalStatus === ''divorced'''),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideMarriageCertNumber', 'text',
   'رقم وثيقة الزواج', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 11, TRUE, '(data) => data.brideMaritalStatus === ''widow'''),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideMarriageCertPlace', 'text',
   'مكان إصدار وثيقة الزواج', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 12, TRUE, '(data) => data.brideMaritalStatus === ''widow'''),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideMarriageCertDate', 'date',
   'تاريخ إصدار وثيقة الزواج', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 13, TRUE, '(data) => data.brideMaritalStatus === ''widow'''),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideHusbandDeathCertNumber', 'text',
   'رقم شهادة وفاة الزوج', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 14, TRUE, '(data) => data.brideMaritalStatus === ''widow'''),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideHusbandDeathCertPlace', 'text',
   'مكان إصدار شهادة الوفاة', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 15, TRUE, '(data) => data.brideMaritalStatus === ''widow'''),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideHusbandDeathCertDate', 'date',
   'تاريخ إصدار شهادة الوفاة', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 16, TRUE, '(data) => data.brideMaritalStatus === ''widow'''),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideInheritanceDocNumber', 'text',
   'رقم الإعلام الشرعي للوراثة', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 17, TRUE, '(data) => data.brideMaritalStatus === ''widow'''),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideInheritanceDocPlace', 'text',
   'مكان إصدار الإعلام الشرعي', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 18, TRUE, '(data) => data.brideMaritalStatus === ''widow'''),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideInheritanceDocDate', 'date',
   'تاريخ إصدار الإعلام الشرعي', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 19, TRUE, '(data) => data.brideMaritalStatus === ''widow'''),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideAddressKSA', 'text',
   'العنوان بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"العنوان بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 20, TRUE, '{}'::jsonb),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideMobileKSA', 'tel',
   'رقم الجوال بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم الجوال بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 21, TRUE, '{}'::jsonb),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideAddressSudan', 'text',
   'العنوان بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 22, TRUE, '{}'::jsonb),
  ('bride-info', 'بيانات المخطوبة', NULL, 'brideMobileSudan', 'tel',
   'رقم الجوال بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 23, TRUE, '{}'::jsonb),
  ('guardian-info', 'بيانات الولي', NULL, 'guardianFullName', 'text',
   'اسم الولي (رباعي)', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"اسم الولي مطلوب"}'::jsonb, '[]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('guardian-info', 'بيانات الولي', NULL, 'guardianRelationship', 'select',
   'صفة الولي', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صفة الولي مطلوبة"}'::jsonb, '[{"value":"father","label":"أب"},{"value":"uncle","label":"عم"},{"value":"brother","label":"أخ"},{"value":"grandfather","label":"جد"},{"value":"other","label":"أخرى"}]'::jsonb, 1, TRUE, '{}'::jsonb),
  ('guardian-info', 'بيانات الولي', NULL, 'guardianPassportNumber', 'text',
   'رقم جواز السفر', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم جواز السفر مطلوب"}'::jsonb, '[]'::jsonb, 2, TRUE, '{}'::jsonb),
  ('guardian-info', 'بيانات الولي', NULL, 'guardianPassportIssuePlace', 'text',
   'مكان الإصدار', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"مكان إصدار الجواز مطلوب"}'::jsonb, '[]'::jsonb, 3, TRUE, '{}'::jsonb),
  ('guardian-info', 'بيانات الولي', NULL, 'guardianPassportIssueDate', 'date',
   'تاريخ الإصدار', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"تاريخ إصدار الجواز مطلوب"}'::jsonb, '[]'::jsonb, 4, TRUE, '{}'::jsonb),
  ('guardian-info', 'بيانات الولي', NULL, 'guardianAddressKSA', 'text',
   'العنوان بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"العنوان بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 5, TRUE, '{}'::jsonb),
  ('guardian-info', 'بيانات الولي', NULL, 'guardianMobileKSA', 'tel',
   'رقم الجوال بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم الجوال بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 6, TRUE, '{}'::jsonb),
  ('guardian-info', 'بيانات الولي', NULL, 'guardianAddressSudan', 'text',
   'العنوان بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 7, TRUE, '{}'::jsonb),
  ('guardian-info', 'بيانات الولي', NULL, 'guardianMobileSudan', 'tel',
   'رقم الجوال بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 8, TRUE, '{}'::jsonb),
  ('guardian-agent-info', 'بيانات وكيل (الولي) إن وجد', NULL, 'hasGuardianAgent', 'radio',
   'هل يوجد وكيل للولي؟', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"هذا الحقل مطلوب"}'::jsonb, '[{"value":"yes","label":"نعم"},{"value":"no","label":"لا"}]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('guardian-agent-info', 'بيانات وكيل (الولي) إن وجد', NULL, 'guardianAgentFullName', 'text',
   'اسم الوكيل (رباعي)', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 1, TRUE, '(data) => data.hasGuardianAgent === ''yes'''),
  ('guardian-agent-info', 'بيانات وكيل (الولي) إن وجد', NULL, 'guardianAgentPassportNumber', 'text',
   'رقم جواز السفر', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 2, TRUE, '(data) => data.hasGuardianAgent === ''yes'''),
  ('guardian-agent-info', 'بيانات وكيل (الولي) إن وجد', NULL, 'guardianAgentPassportIssuePlace', 'text',
   'مكان الإصدار', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 3, TRUE, '(data) => data.hasGuardianAgent === ''yes'''),
  ('guardian-agent-info', 'بيانات وكيل (الولي) إن وجد', NULL, 'guardianAgentPassportIssueDate', 'date',
   'تاريخ الإصدار', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 4, TRUE, '(data) => data.hasGuardianAgent === ''yes'''),
  ('guardian-agent-info', 'بيانات وكيل (الولي) إن وجد', NULL, 'guardianAgentPoaNumber', 'text',
   'رقم التوكيل', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 5, TRUE, '(data) => data.hasGuardianAgent === ''yes'''),
  ('guardian-agent-info', 'بيانات وكيل (الولي) إن وجد', NULL, 'guardianAgentPoaDate', 'date',
   'تاريخ التوكيل', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 6, TRUE, '(data) => data.hasGuardianAgent === ''yes'''),
  ('guardian-agent-info', 'بيانات وكيل (الولي) إن وجد', NULL, 'guardianAgentPoaIssuer', 'text',
   'جهة إصدار التوكيل', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 7, TRUE, '(data) => data.hasGuardianAgent === ''yes'''),
  ('guardian-agent-info', 'بيانات وكيل (الولي) إن وجد', NULL, 'guardianAgentAddressKSA', 'text',
   'العنوان بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 8, TRUE, '(data) => data.hasGuardianAgent === ''yes'''),
  ('guardian-agent-info', 'بيانات وكيل (الولي) إن وجد', NULL, 'guardianAgentMobileKSA', 'tel',
   'رقم الجوال بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 9, TRUE, '(data) => data.hasGuardianAgent === ''yes'''),
  ('guardian-agent-info', 'بيانات وكيل (الولي) إن وجد', NULL, 'guardianAgentAddressSudan', 'text',
   'العنوان بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 10, TRUE, '(data) => data.hasGuardianAgent === ''yes'''),
  ('guardian-agent-info', 'بيانات وكيل (الولي) إن وجد', NULL, 'guardianAgentMobileSudan', 'tel',
   'رقم الجوال بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 11, TRUE, '(data) => data.hasGuardianAgent === ''yes'''),
  ('groom-agent-info', 'بيانات وكيل (الزوج) إن وجد', NULL, 'hasGroomAgent', 'radio',
   'هل يوجد وكيل للزوج؟', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"هذا الحقل مطلوب"}'::jsonb, '[{"value":"yes","label":"نعم"},{"value":"no","label":"لا"}]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('groom-agent-info', 'بيانات وكيل (الزوج) إن وجد', NULL, 'groomAgentFullName', 'text',
   'اسم الوكيل (رباعي)', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 1, TRUE, '(data) => data.hasGroomAgent === ''yes'''),
  ('groom-agent-info', 'بيانات وكيل (الزوج) إن وجد', NULL, 'groomAgentPassportNumber', 'text',
   'رقم جواز السفر', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 2, TRUE, '(data) => data.hasGroomAgent === ''yes'''),
  ('groom-agent-info', 'بيانات وكيل (الزوج) إن وجد', NULL, 'groomAgentPassportIssuePlace', 'text',
   'مكان الإصدار', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 3, TRUE, '(data) => data.hasGroomAgent === ''yes'''),
  ('groom-agent-info', 'بيانات وكيل (الزوج) إن وجد', NULL, 'groomAgentPassportIssueDate', 'date',
   'تاريخ الإصدار', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 4, TRUE, '(data) => data.hasGroomAgent === ''yes'''),
  ('groom-agent-info', 'بيانات وكيل (الزوج) إن وجد', NULL, 'groomAgentPoaNumber', 'text',
   'رقم التوكيل', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 5, TRUE, '(data) => data.hasGroomAgent === ''yes'''),
  ('groom-agent-info', 'بيانات وكيل (الزوج) إن وجد', NULL, 'groomAgentPoaDate', 'date',
   'تاريخ التوكيل', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 6, TRUE, '(data) => data.hasGroomAgent === ''yes'''),
  ('groom-agent-info', 'بيانات وكيل (الزوج) إن وجد', NULL, 'groomAgentPoaIssuer', 'text',
   'جهة إصدار التوكيل', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 7, TRUE, '(data) => data.hasGroomAgent === ''yes'''),
  ('groom-agent-info', 'بيانات وكيل (الزوج) إن وجد', NULL, 'groomAgentAddressKSA', 'text',
   'العنوان بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 8, TRUE, '(data) => data.hasGroomAgent === ''yes'''),
  ('groom-agent-info', 'بيانات وكيل (الزوج) إن وجد', NULL, 'groomAgentMobileKSA', 'tel',
   'رقم الجوال بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 9, TRUE, '(data) => data.hasGroomAgent === ''yes'''),
  ('groom-agent-info', 'بيانات وكيل (الزوج) إن وجد', NULL, 'groomAgentAddressSudan', 'text',
   'العنوان بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 10, TRUE, '(data) => data.hasGroomAgent === ''yes'''),
  ('groom-agent-info', 'بيانات وكيل (الزوج) إن وجد', NULL, 'groomAgentMobileSudan', 'tel',
   'رقم الجوال بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 11, TRUE, '(data) => data.hasGroomAgent === ''yes'''),
  ('dowry-info', 'بيانات الصداق (المهر)', NULL, 'dowryTotal', 'number',
   'الصداق', NULL, NULL, NULL, 'المبلغ الإجمالي للصداق', NULL, NULL,
   true, '{"required":"الصداق مطلوب"}'::jsonb, '[]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('dowry-info', 'بيانات الصداق (المهر)', NULL, 'dowryPaid', 'number',
   'المقبوض', NULL, NULL, NULL, 'المبلغ المدفوع مقدماً', NULL, NULL,
   true, '{"required":"المقبوض مطلوب"}'::jsonb, '[]'::jsonb, 1, TRUE, '{}'::jsonb),
  ('dowry-info', 'بيانات الصداق (المهر)', NULL, 'dowryDeferred', 'number',
   'المؤخر', NULL, NULL, NULL, 'المبلغ المؤجل', NULL, NULL,
   true, '{"required":"المؤخر مطلوب"}'::jsonb, '[]'::jsonb, 2, TRUE, '{}'::jsonb),
  ('witnesses-info', 'الشهود', NULL, 'witness1FullName', 'text',
   'اسم الشاهد الأول (رباعي)', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"اسم الشاهد الأول مطلوب"}'::jsonb, '[]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('witnesses-info', 'الشهود', NULL, 'witness1PassportNumber', 'text',
   'رقم جواز السفر', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم جواز السفر مطلوب"}'::jsonb, '[]'::jsonb, 1, TRUE, '{}'::jsonb),
  ('witnesses-info', 'الشهود', NULL, 'witness1AddressKSA', 'text',
   'العنوان بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"العنوان بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 2, TRUE, '{}'::jsonb),
  ('witnesses-info', 'الشهود', NULL, 'witness1MobileKSA', 'tel',
   'رقم الجوال بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم الجوال بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 3, TRUE, '{}'::jsonb),
  ('witnesses-info', 'الشهود', NULL, 'witness1AddressSudan', 'text',
   'العنوان بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 4, TRUE, '{}'::jsonb),
  ('witnesses-info', 'الشهود', NULL, 'witness1MobileSudan', 'tel',
   'رقم الجوال بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 5, TRUE, '{}'::jsonb),
  ('witnesses-info', 'الشهود', NULL, 'witness2FullName', 'text',
   'اسم الشاهد الثاني (رباعي)', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"اسم الشاهد الثاني مطلوب"}'::jsonb, '[]'::jsonb, 6, TRUE, '{}'::jsonb),
  ('witnesses-info', 'الشهود', NULL, 'witness2PassportNumber', 'text',
   'رقم جواز السفر', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم جواز السفر مطلوب"}'::jsonb, '[]'::jsonb, 7, TRUE, '{}'::jsonb),
  ('witnesses-info', 'الشهود', NULL, 'witness2AddressKSA', 'text',
   'العنوان بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"العنوان بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 8, TRUE, '{}'::jsonb),
  ('witnesses-info', 'الشهود', NULL, 'witness2MobileKSA', 'tel',
   'رقم الجوال بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم الجوال بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 9, TRUE, '{}'::jsonb),
  ('witnesses-info', 'الشهود', NULL, 'witness2AddressSudan', 'text',
   'العنوان بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 10, TRUE, '{}'::jsonb),
  ('witnesses-info', 'الشهود', NULL, 'witness2MobileSudan', 'tel',
   'رقم الجوال بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 11, TRUE, '{}'::jsonb),
  ('appointment-info', 'الموعد المقترح لعقد الزواج', NULL, 'appointmentNote', 'info',
   'معلومات الموعد', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('appointment-info', 'الموعد المقترح لعقد الزواج', NULL, 'proposedAppointmentDate', 'date',
   'الموعد المقترح', NULL, NULL, NULL, 'اختر الموعد المناسب لك (من الأحد إلى الخميس)', NULL, NULL,
   true, '{"required":"الموعد المقترح مطلوب"}'::jsonb, '[]'::jsonb, 1, TRUE, '{}'::jsonb),
  ('husband-info', 'بيانات الزوج (المطلق)', NULL, 'husbandFullName', 'text',
   'اسم الزوج الكامل (رباعي)', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"اسم الزوج مطلوب"}'::jsonb, '[]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('husband-info', 'بيانات الزوج (المطلق)', NULL, 'husbandBirthDate', 'date',
   'تاريخ الميلاد', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"تاريخ الميلاد مطلوب"}'::jsonb, '[]'::jsonb, 1, TRUE, '{}'::jsonb),
  ('husband-info', 'بيانات الزوج (المطلق)', NULL, 'husbandNationalId', 'text',
   'الرقم الوطني', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"الرقم الوطني مطلوب"}'::jsonb, '[]'::jsonb, 2, TRUE, '{}'::jsonb),
  ('husband-info', 'بيانات الزوج (المطلق)', NULL, 'husbandPassportNumber', 'text',
   'رقم جواز السفر', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم جواز السفر مطلوب"}'::jsonb, '[]'::jsonb, 3, TRUE, '{}'::jsonb),
  ('husband-info', 'بيانات الزوج (المطلق)', NULL, 'husbandPassportIssuePlace', 'text',
   'مكان إصدار الجواز', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"مكان إصدار الجواز مطلوب"}'::jsonb, '[]'::jsonb, 4, TRUE, '{}'::jsonb),
  ('husband-info', 'بيانات الزوج (المطلق)', NULL, 'husbandPassportIssueDate', 'date',
   'تاريخ إصدار الجواز', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"تاريخ إصدار الجواز مطلوب"}'::jsonb, '[]'::jsonb, 5, TRUE, '{}'::jsonb),
  ('husband-info', 'بيانات الزوج (المطلق)', NULL, 'husbandResidenceStatus', 'select',
   'حالة الإقامة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"حالة الإقامة مطلوبة"}'::jsonb, '[{"value":"resident","label":"مقيم"},{"value":"visitor","label":"زيارة"},{"value":"umrah","label":"عمرة"}]'::jsonb, 6, TRUE, '{}'::jsonb),
  ('husband-info', 'بيانات الزوج (المطلق)', NULL, 'husbandResidenceNumber', 'text',
   'رقم الإقامة', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 7, TRUE, '(data) => data.husbandResidenceStatus === ''resident'''),
  ('husband-info', 'بيانات الزوج (المطلق)', NULL, 'husbandOccupation', 'text',
   'المهنة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"المهنة مطلوبة"}'::jsonb, '[]'::jsonb, 8, TRUE, '{}'::jsonb),
  ('husband-info', 'بيانات الزوج (المطلق)', NULL, 'husbandAddressKSA', 'text',
   'العنوان بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"العنوان بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 9, TRUE, '{}'::jsonb),
  ('husband-info', 'بيانات الزوج (المطلق)', NULL, 'husbandMobileKSA', 'tel',
   'رقم الجوال بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم الجوال بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 10, TRUE, '{}'::jsonb),
  ('husband-info', 'بيانات الزوج (المطلق)', NULL, 'husbandAddressSudan', 'text',
   'العنوان بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 11, TRUE, '{}'::jsonb),
  ('husband-info', 'بيانات الزوج (المطلق)', NULL, 'husbandMobileSudan', 'tel',
   'رقم الجوال بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 12, TRUE, '{}'::jsonb),
  ('marriage-details', 'بيانات الزواج', NULL, 'marriageCertNumber', 'text',
   'رقم وثيقة الزواج', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم وثيقة الزواج مطلوب"}'::jsonb, '[]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('marriage-details', 'بيانات الزواج', NULL, 'marriageDate', 'date',
   'تاريخ الزواج', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"تاريخ الزواج مطلوب"}'::jsonb, '[]'::jsonb, 1, TRUE, '{}'::jsonb),
  ('marriage-details', 'بيانات الزواج', NULL, 'marriagePlace', 'text',
   'مكان الزواج', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"مكان الزواج مطلوب"}'::jsonb, '[]'::jsonb, 2, TRUE, '{}'::jsonb),
  ('marriage-details', 'بيانات الزواج', NULL, 'marriageIssuer', 'text',
   'جهة إصدار وثيقة الزواج', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"جهة الإصدار مطلوبة"}'::jsonb, '[]'::jsonb, 3, TRUE, '{}'::jsonb),
  ('marriage-details', 'بيانات الزواج', NULL, 'dowryPaid', 'number',
   'المهر المقبوض', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"المهر المقبوض مطلوب"}'::jsonb, '[]'::jsonb, 4, TRUE, '{}'::jsonb),
  ('marriage-details', 'بيانات الزواج', NULL, 'dowryDeferred', 'number',
   'المهر المؤخر', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"المهر المؤخر مطلوب"}'::jsonb, '[]'::jsonb, 5, TRUE, '{}'::jsonb),
  ('divorce-details', 'بيانات الطلاق', NULL, 'divorceType', 'select',
   'نوع الطلاق', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"نوع الطلاق مطلوب"}'::jsonb, '[{"value":"revocable","label":"طلاق رجعي"},{"value":"irrevocable_minor","label":"طلاق بائن بينونة صغرى"},{"value":"irrevocable_major","label":"طلاق بائن بينونة كبرى"}]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('divorce-details', 'بيانات الطلاق', NULL, 'divorceCount', 'select',
   'عدد الطلقات', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"عدد الطلقات مطلوب"}'::jsonb, '[{"value":"first","label":"طلقة أولى"},{"value":"second","label":"طلقة ثانية"},{"value":"third","label":"طلقة ثالثة"}]'::jsonb, 1, TRUE, '{}'::jsonb),
  ('divorce-details', 'بيانات الطلاق', NULL, 'divorceDate', 'date',
   'تاريخ وقوع الطلاق', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"تاريخ وقوع الطلاق مطلوب"}'::jsonb, '[]'::jsonb, 2, TRUE, '{}'::jsonb),
  ('divorce-details', 'بيانات الطلاق', NULL, 'divorcePlace', 'text',
   'مكان وقوع الطلاق', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"مكان وقوع الطلاق مطلوب"}'::jsonb, '[]'::jsonb, 3, TRUE, '{}'::jsonb),
  ('divorce-details', 'بيانات الطلاق', NULL, 'divorceReason', 'textarea',
   'سبب الطلاق', NULL, NULL, NULL, 'اختياري - يمكنك ذكر سبب الطلاق', NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 4, TRUE, '{}'::jsonb),
  ('divorce-declaration', 'إقرار الطلاق', NULL, 'divorceDeclarationCheckbox', 'checkbox',
   'أقر بكامل قواي العقلية وإرادتي الحرة المعتبرة شرعاً وقانوناً بأنني قد طلقت زوجتي المذكورة أعلاه', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"يجب الموافقة على الإقرار"}'::jsonb, '[]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('divorce-declaration', 'إقرار الطلاق', NULL, 'divorceAcknowledgment', 'checkbox',
   'وهذا إقرار مني بذلك', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"يجب الموافقة على الإقرار"}'::jsonb, '[]'::jsonb, 1, TRUE, '{}'::jsonb),
  ('wife-info', 'بيانات الزوجة (المطلقة)', NULL, 'wifeFullName', 'text',
   'اسم الزوجة الكامل (رباعي)', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"اسم الزوجة مطلوب"}'::jsonb, '[]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('wife-info', 'بيانات الزوجة (المطلقة)', NULL, 'wifeBirthDate', 'date',
   'تاريخ الميلاد', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"تاريخ الميلاد مطلوب"}'::jsonb, '[]'::jsonb, 1, TRUE, '{}'::jsonb),
  ('wife-info', 'بيانات الزوجة (المطلقة)', NULL, 'wifeNationalId', 'text',
   'الرقم الوطني', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"الرقم الوطني مطلوب"}'::jsonb, '[]'::jsonb, 2, TRUE, '{}'::jsonb),
  ('wife-info', 'بيانات الزوجة (المطلقة)', NULL, 'wifePassportNumber', 'text',
   'رقم جواز السفر', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم جواز السفر مطلوب"}'::jsonb, '[]'::jsonb, 3, TRUE, '{}'::jsonb),
  ('wife-info', 'بيانات الزوجة (المطلقة)', NULL, 'wifePassportIssuePlace', 'text',
   'مكان إصدار الجواز', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"مكان إصدار الجواز مطلوب"}'::jsonb, '[]'::jsonb, 4, TRUE, '{}'::jsonb),
  ('wife-info', 'بيانات الزوجة (المطلقة)', NULL, 'wifePassportIssueDate', 'date',
   'تاريخ إصدار الجواز', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"تاريخ إصدار الجواز مطلوب"}'::jsonb, '[]'::jsonb, 5, TRUE, '{}'::jsonb),
  ('wife-info', 'بيانات الزوجة (المطلقة)', NULL, 'wifeResidenceStatus', 'select',
   'حالة الإقامة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"حالة الإقامة مطلوبة"}'::jsonb, '[{"value":"resident","label":"مقيم"},{"value":"visitor","label":"زيارة"},{"value":"umrah","label":"عمرة"}]'::jsonb, 6, TRUE, '{}'::jsonb),
  ('wife-info', 'بيانات الزوجة (المطلقة)', NULL, 'wifeResidenceNumber', 'text',
   'رقم الإقامة', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 7, TRUE, '(data) => data.wifeResidenceStatus === ''resident'''),
  ('wife-info', 'بيانات الزوجة (المطلقة)', NULL, 'wifeOccupation', 'text',
   'المهنة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"المهنة مطلوبة"}'::jsonb, '[]'::jsonb, 8, TRUE, '{}'::jsonb),
  ('wife-info', 'بيانات الزوجة (المطلقة)', NULL, 'wifeAddressKSA', 'text',
   'العنوان بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"العنوان بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 9, TRUE, '{}'::jsonb),
  ('wife-info', 'بيانات الزوجة (المطلقة)', NULL, 'wifeMobileKSA', 'tel',
   'رقم الجوال بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم الجوال بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 10, TRUE, '{}'::jsonb),
  ('wife-info', 'بيانات الزوجة (المطلقة)', NULL, 'wifeAddressSudan', 'text',
   'العنوان بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 11, TRUE, '{}'::jsonb),
  ('wife-info', 'بيانات الزوجة (المطلقة)', NULL, 'wifeMobileSudan', 'tel',
   'رقم الجوال بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 12, TRUE, '{}'::jsonb),
  ('divorce-witnesses', 'بيانات الشهود', NULL, 'witness1FullName', 'text',
   'اسم الشاهد الأول (رباعي)', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"اسم الشاهد الأول مطلوب"}'::jsonb, '[]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('divorce-witnesses', 'بيانات الشهود', NULL, 'witness1PassportNumber', 'text',
   'رقم جواز السفر', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم جواز السفر مطلوب"}'::jsonb, '[]'::jsonb, 1, TRUE, '{}'::jsonb),
  ('divorce-witnesses', 'بيانات الشهود', NULL, 'witness1AddressKSA', 'text',
   'العنوان بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"العنوان بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 2, TRUE, '{}'::jsonb),
  ('divorce-witnesses', 'بيانات الشهود', NULL, 'witness1MobileKSA', 'tel',
   'رقم الجوال بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم الجوال بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 3, TRUE, '{}'::jsonb),
  ('divorce-witnesses', 'بيانات الشهود', NULL, 'witness1AddressSudan', 'text',
   'العنوان بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 4, TRUE, '{}'::jsonb),
  ('divorce-witnesses', 'بيانات الشهود', NULL, 'witness1MobileSudan', 'tel',
   'رقم الجوال بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 5, TRUE, '{}'::jsonb),
  ('divorce-witnesses', 'بيانات الشهود', NULL, 'witness2FullName', 'text',
   'اسم الشاهد الثاني (رباعي)', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"اسم الشاهد الثاني مطلوب"}'::jsonb, '[]'::jsonb, 6, TRUE, '{}'::jsonb),
  ('divorce-witnesses', 'بيانات الشهود', NULL, 'witness2PassportNumber', 'text',
   'رقم جواز السفر', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم جواز السفر مطلوب"}'::jsonb, '[]'::jsonb, 7, TRUE, '{}'::jsonb),
  ('divorce-witnesses', 'بيانات الشهود', NULL, 'witness2AddressKSA', 'text',
   'العنوان بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"العنوان بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 8, TRUE, '{}'::jsonb),
  ('divorce-witnesses', 'بيانات الشهود', NULL, 'witness2MobileKSA', 'tel',
   'رقم الجوال بالسعودية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"رقم الجوال بالسعودية مطلوب"}'::jsonb, '[]'::jsonb, 9, TRUE, '{}'::jsonb),
  ('divorce-witnesses', 'بيانات الشهود', NULL, 'witness2AddressSudan', 'text',
   'العنوان بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 10, TRUE, '{}'::jsonb),
  ('divorce-witnesses', 'بيانات الشهود', NULL, 'witness2MobileSudan', 'tel',
   'رقم الجوال بالسودان', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 11, TRUE, '{}'::jsonb),
  ('documents', 'المستندات المطلوبة', NULL, 'groomPassportCopy', 'file',
   'إثبات شخصية الخاطب (الجواز أو الرقم الوطني)', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"إثبات شخصية الخاطب مطلوب"}'::jsonb, '[]'::jsonb, 0, TRUE, '(data) => data.serviceType === ''marriage'''),
  ('documents', 'المستندات المطلوبة', NULL, 'bridePassportCopy', 'file',
   'إثبات شخصية المخطوبة (الجواز أو الرقم الوطني)', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"إثبات شخصية المخطوبة مطلوب"}'::jsonb, '[]'::jsonb, 1, TRUE, '(data) => data.serviceType === ''marriage'''),
  ('documents', 'المستندات المطلوبة', NULL, 'guardianPassportCopy', 'file',
   'إثبات شخصية ولي المخطوبة (الأب)', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"إثبات شخصية الولي مطلوب"}'::jsonb, '[]'::jsonb, 2, TRUE, '(data) => data.serviceType === ''marriage'''),
  ('documents', 'المستندات المطلوبة', NULL, 'witness1PassportCopy', 'file',
   'إثبات شخصية الشاهد الأول', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"إثبات شخصية الشاهد الأول مطلوب"}'::jsonb, '[]'::jsonb, 3, TRUE, '(data) => data.serviceType === ''marriage'''),
  ('documents', 'المستندات المطلوبة', NULL, 'witness2PassportCopy', 'file',
   'إثبات شخصية الشاهد الثاني', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"إثبات شخصية الشاهد الثاني مطلوب"}'::jsonb, '[]'::jsonb, 4, TRUE, '(data) => data.serviceType === ''marriage'''),
  ('documents', 'المستندات المطلوبة', NULL, 'brideConsentLetter', 'file',
   'إقرار موافقة المخطوبة على الزواج (في حال غياب المخطوبة)', NULL, NULL, NULL, 'في حال كانت المخطوبة غائبة عن مجلس العقد', NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 5, TRUE, '(data) => data.serviceType === ''marriage'''),
  ('documents', 'المستندات المطلوبة', NULL, 'brideDivorceCert', 'file',
   'أصل وثيقة الطلاق موثقة من الخارجية السودانية (في حال كانت المخطوبة مطلقة)', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 6, TRUE, '(data) => data.serviceType === ''marriage'' && data.brideMaritalStatus === ''divorced'''),
  ('documents', 'المستندات المطلوبة', NULL, 'brideWidowDocs', 'file',
   'وثيقة الزواج وشهادة وفاة الزوج أو الإعلام الشرعي للورثة (في حال كانت المخطوبة أرملة)', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 7, TRUE, '(data) => data.serviceType === ''marriage'' && data.brideMaritalStatus === ''widow'''),
  ('documents', 'المستندات المطلوبة', NULL, 'guardianPowerOfAttorney', 'file',
   'توكيل الولي موثق من الخارجية السودانية (في حال غياب والد المخطوبة)', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 8, TRUE, '(data) => data.serviceType === ''marriage'' && data.hasGuardianAgent === ''yes'''),
  ('documents', 'المستندات المطلوبة', NULL, 'guardianDeathCert', 'file',
   'إثبات وفاة الولي أو الإعلام الشرعي للوراثة (في حال وفاة ولي المخطوبة)', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 9, TRUE, '(data) => data.serviceType === ''marriage'''),
  ('documents', 'المستندات المطلوبة', NULL, 'divorceReceipt', 'file',
   'القسيمة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"القسيمة مطلوبة"}'::jsonb, '[]'::jsonb, 10, TRUE, '(data) => data.serviceType === ''divorce'''),
  ('documents', 'المستندات المطلوبة', NULL, 'husbandPassportCopy', 'file',
   'صورة جواز الزوج', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة جواز الزوج مطلوبة"}'::jsonb, '[]'::jsonb, 11, TRUE, '(data) => data.serviceType === ''divorce'''),
  ('documents', 'المستندات المطلوبة', NULL, 'wifePassportCopy', 'file',
   'صورة جواز الزوجة', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة جواز الزوجة مطلوبة"}'::jsonb, '[]'::jsonb, 12, TRUE, '(data) => data.serviceType === ''divorce'''),
  ('documents', 'المستندات المطلوبة', NULL, 'divorceWitness1PassportCopy', 'file',
   'صورة جواز الشاهد الأول', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة جواز الشاهد الأول مطلوبة"}'::jsonb, '[]'::jsonb, 13, TRUE, '(data) => data.serviceType === ''divorce'''),
  ('documents', 'المستندات المطلوبة', NULL, 'divorceWitness2PassportCopy', 'file',
   'صورة جواز الشاهد الثاني', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"صورة جواز الشاهد الثاني مطلوبة"}'::jsonb, '[]'::jsonb, 14, TRUE, '(data) => data.serviceType === ''divorce'''),
  ('documents', 'المستندات المطلوبة', NULL, 'additionalDocuments', 'file',
   'مستندات إضافية إن وجد', NULL, NULL, NULL, NULL, NULL, NULL,
   false, '{}'::jsonb, '[]'::jsonb, 15, TRUE, '(data) => data.serviceType === ''divorce'''),
  ('acknowledgment', 'الإقرار', NULL, 'personalAttendance', 'checkbox',
   'أقر بأن جميع الأطراف والشهود سيحضرون شخصياً مع جوازات السفر الأصلية', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"يجب الموافقة على الحضور الشخصي"}'::jsonb, '[]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('acknowledgment', 'الإقرار', NULL, 'dataAccuracy', 'checkbox',
   'أتعهد بصحة جميع البيانات المذكورة أعلاه', NULL, NULL, NULL, NULL, NULL, NULL,
   true, '{"required":"يجب تأكيد صحة البيانات"}'::jsonb, '[]'::jsonb, 1, TRUE, '{}'::jsonb)
) AS fld(
  step_id, step_title_ar, step_title_en, field_name, field_type, label_ar, label_en,
  placeholder_ar, placeholder_en, help_text_ar, help_text_en, default_value,
  is_required, validation_rules, options, order_index, is_active, conditions
)
WHERE services.slug = 'madhoonia';

-- إدراج المرفقات
INSERT INTO service_documents (
  service_id, document_name_ar, document_name_en, description_ar, description_en,
  is_required, max_size_mb, accepted_formats, order_index, is_active, conditions
)
SELECT id, * FROM services, (VALUES
  ('إثبات شخصية الخاطب (الجواز أو الرقم الوطني)', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 0, TRUE, '{}'::jsonb),
  ('إثبات شخصية المخطوبة (الجواز أو الرقم الوطني)', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 1, TRUE, '{}'::jsonb),
  ('إثبات شخصية ولي المخطوبة (الأب)', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 2, TRUE, '{}'::jsonb),
  ('إثبات شخصية الشاهد الأول', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 3, TRUE, '{}'::jsonb),
  ('إثبات شخصية الشاهد الثاني', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 4, TRUE, '{}'::jsonb),
  ('إقرار موافقة المخطوبة على الزواج (في حال غياب المخطوبة)', NULL, 'في حال كانت المخطوبة غائبة عن مجلس العقد', NULL,
   false, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 5, TRUE, '{}'::jsonb),
  ('أصل وثيقة الطلاق موثقة من الخارجية السودانية (في حال كانت المخطوبة مطلقة)', NULL, NULL, NULL,
   false, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 6, TRUE, '{}'::jsonb),
  ('وثيقة الزواج وشهادة وفاة الزوج أو الإعلام الشرعي للورثة (في حال كانت المخطوبة أرملة)', NULL, NULL, NULL,
   false, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 7, TRUE, '{}'::jsonb),
  ('توكيل الولي موثق من الخارجية السودانية (في حال غياب والد المخطوبة)', NULL, NULL, NULL,
   false, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 8, TRUE, '{}'::jsonb),
  ('إثبات وفاة الولي أو الإعلام الشرعي للوراثة (في حال وفاة ولي المخطوبة)', NULL, NULL, NULL,
   false, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 9, TRUE, '{}'::jsonb),
  ('القسيمة', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 10, TRUE, '{}'::jsonb),
  ('صورة جواز الزوج', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 11, TRUE, '{}'::jsonb),
  ('صورة جواز الزوجة', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 12, TRUE, '{}'::jsonb),
  ('صورة جواز الشاهد الأول', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 13, TRUE, '{}'::jsonb),
  ('صورة جواز الشاهد الثاني', NULL, NULL, NULL,
   true, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 14, TRUE, '{}'::jsonb),
  ('مستندات إضافية إن وجد', NULL, NULL, NULL,
   false, 5, '["pdf","jpg","jpeg","png"]'::jsonb, 15, TRUE, '{}'::jsonb)
) AS doc(document_name_ar, document_name_en, description_ar, description_en,
  is_required, max_size_mb, accepted_formats, order_index, is_active, conditions)
WHERE services.slug = 'madhoonia';

